//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AlarmKindDAOImpl.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//

package com.soloud.per.daoimpl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;

import com.soloud.per.dao.AlarmKindDeleteDAO;
import com.soloud.per.dao.AlarmKindInsertDAO;
import com.soloud.per.dao.AlarmKindSearchDAO;
import com.soloud.per.dao.AlarmKindUpdateDAO;
import com.soloud.per.dao.BaseDAO;
import com.soloud.per.dto.AlarmKindDTO;




public class AlarmKindDAOImpl extends BaseDAO implements AlarmKindSearchDAO, AlarmKindInsertDAO, AlarmKindUpdateDAO, AlarmKindDeleteDAO
{

	public List<AlarmKindDTO> searchAllAlarmKind()
	{
		final List<AlarmKindDTO> temp = new ArrayList<AlarmKindDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM alarm_kind_tb";
		jt.query(sql, new RowCallbackHandler() 
			{
				@Override
				public void processRow(ResultSet rs) throws SQLException 
				{
					//System.out.println(rs.getString("alarm_kind_code"));
					// TODO Auto-generated method stub
					while(true)
					{
						AlarmKindDTO tmp = new AlarmKindDTO();
						tmp.setAlarmKindCode(rs.getString("alarm_kind_code"));
						tmp.setAlarmKindName(rs.getString("alarm_kind_name"));
						temp.add(tmp);
						if(rs.next()==false)
						{
							break;
						}
					}
				}
			});
		return temp;

	}
	
	public AlarmKindDTO searchAlarmKindCode(String alarmKindCode)
	{
		final List<AlarmKindDTO> temp = new ArrayList<AlarmKindDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM alarm_kind_tb WHERE alarm_kind_code=\'" + alarmKindCode + "\'";
		
		
		jt.query(sql,new RowCallbackHandler() 
		{
			@Override
			public void processRow(ResultSet rs) throws SQLException 
			{
				//System.out.println(rs.getString("alarm_kind_code"));
				// TODO Auto-generated method stub
				while(true)
				{
					AlarmKindDTO tmp = new AlarmKindDTO();
					tmp.setAlarmKindCode(rs.getString("alarm_kind_code"));
					tmp.setAlarmKindName(rs.getString("alarm_kind_name"));
					temp.add(tmp);
					if(rs.next()==false)
					{
						break;
					}
				}
			}
		});
		return temp.get(0);
	}
	
	public List<AlarmKindDTO> searchAlarmKindName(String alarmKindName)
	{
		final List<AlarmKindDTO> temp = new ArrayList<AlarmKindDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM alarm_kind_tb WHERE alarm_kind_name=\'" + alarmKindName + "\'";
		
		
		jt.query(sql,new RowCallbackHandler() 
		{
			@Override
			public void processRow(ResultSet rs) throws SQLException 
			{
				//System.out.println(rs.getString("alarm_kind_code"));
				// TODO Auto-generated method stub
				while(true)
				{
					AlarmKindDTO tmp = new AlarmKindDTO();
					tmp.setAlarmKindCode(rs.getString("alarm_kind_code"));
					tmp.setAlarmKindName(rs.getString("alarm_kind_name"));
					temp.add(tmp);
					if(rs.next()==false)
					{
						break;
					}
				}
			}
		});
		return temp;
	}
	
	public int updatedAlarmKindName(final String alarmKindCode, final String alarmKindName)
	{
		JdbcTemplate jt = getJdbcTemplate();
		final String sql = "UPDATE alarm_kind_tb" 
		+" SET alarm_kind_name="
		+"\'" + alarmKindName + "\'"
		+" WHERE alarm_kind_code="
		+"\'" + alarmKindCode + "\'";

		int res = jt.update(sql);
		
		return res;
	}
	@Override
	public boolean insertAlarmKindDTO(AlarmKindDTO dto) {
		// TODO Auto-generated method stub
		JdbcTemplate jt = getJdbcTemplate();
		String sql = "INSERT INTO alarm_kind_tb VALUES ("
					+"'"+dto.getAlarmKindCode() + "','"
					+dto.getAlarmKindName() + "')";
		
		
		
		int res = jt.update(sql);
		if(res>0)
		{
			return true;
		}
		else
		{
			return false;
		}
		
	}
	
	public boolean insertAlarmKind(String alarmKindName)
	{
		JdbcTemplate jt = getJdbcTemplate();
		String sql = "INSERT INTO alarm_kind_tb VALUES (\'ak\' || alarm_kind_sequence.nextval, ?)";
		
		
		Object[] params = new Object[]{alarmKindName};
		int[] types = new int[]{Types.VARCHAR};
		
		int res = jt.update(sql, params, types);
		
		if(res>0)
		{
			return true;
		}
		else
		{
			return false;
		}
		
	}
	
	public int deleteAlarmKindCode(String alarmKindCode)
	{
		
		JdbcTemplate jt = getJdbcTemplate();
		
		String sql = "DELETE FROM alarm_kind_tb WHERE alarm_kind_code ='" + alarmKindCode + "'";
		
		int res = jt.update(sql);


		return res;
	}
	
	public int deleteAlarmKindName(String alarmKindName)
	{
		JdbcTemplate jt = getJdbcTemplate();
		
		String sql = "DELETE FROM alarm_kind_tb WHERE alarm_kind_name = ? ";
		
		Object[] params = new Object[]{alarmKindName};
		int[] types = new int[]{Types.VARCHAR};
		
		int res = jt.update(sql, params, types);

		return res;
	}

	
}
