//
//

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AvailableFileAuthGroupDAOImpl.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.daoimpl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;

import com.soloud.per.dao.AvailableFileAuthGroupDeleteDAO;
import com.soloud.per.dao.AvailableFileAuthGroupInsertDAO;
import com.soloud.per.dao.AvailableFileAuthGroupSearchDAO;
import com.soloud.per.dao.AvailableFileAuthGroupUpdateDAO;
import com.soloud.per.dao.BaseDAO;
import com.soloud.per.dto.AvailableFileAuthGroupDTO;





public class AvailableFileAuthGroupDAOImpl extends BaseDAO implements AvailableFileAuthGroupSearchDAO, AvailableFileAuthGroupInsertDAO, AvailableFileAuthGroupUpdateDAO, AvailableFileAuthGroupDeleteDAO
{
	public List<AvailableFileAuthGroupDTO> searchAllAFAG()
	{
		final List<AvailableFileAuthGroupDTO> temp = new ArrayList<AvailableFileAuthGroupDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM available_file_auth_group_tb";
		jt.query(sql, new RowCallbackHandler() 
			{
				@Override
				public void processRow(ResultSet rs) throws SQLException 
				{
					//System.out.println(rs.getString("alarm_kind_code"));
					// TODO Auto-generated method stub
					while(true)
					{
						AvailableFileAuthGroupDTO tmp = new AvailableFileAuthGroupDTO();
						tmp.setFileCode(rs.getString("file_code"));
						tmp.setGroupCode(rs.getString("group_code"));
						temp.add(tmp);
						if(rs.next()==false)
						{
							break;
						}
					}
				}
			});
		return temp;
	}
	
	public List<AvailableFileAuthGroupDTO> searchFileCode(String fileCode)
	{
		final List<AvailableFileAuthGroupDTO> temp = new ArrayList<AvailableFileAuthGroupDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM available_file_auth_group_tb WHERE file_code='" + fileCode + "'" ;
		jt.query(sql, new RowCallbackHandler() 
			{
				@Override
				public void processRow(ResultSet rs) throws SQLException 
				{
					//System.out.println(rs.getString("alarm_kind_code"));
					// TODO Auto-generated method stub
					while(true)
					{
						AvailableFileAuthGroupDTO tmp = new AvailableFileAuthGroupDTO();
						tmp.setFileCode(rs.getString("file_code"));
						tmp.setGroupCode(rs.getString("group_code"));
						temp.add(tmp);
						if(rs.next()==false)
						{
							break;
						}
					}
				}
			});
		return temp;
	
	}
	
	public List<AvailableFileAuthGroupDTO> searchGroupCode(String groupCode)
	{
		final List<AvailableFileAuthGroupDTO> temp = new ArrayList<AvailableFileAuthGroupDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM available_file_auth_group_tb WHERE group_code='" + groupCode + "'" ;
		jt.query(sql, new RowCallbackHandler() 
			{
				@Override
				public void processRow(ResultSet rs) throws SQLException 
				{
					//System.out.println(rs.getString("alarm_kind_code"));
					// TODO Auto-generated method stub
					while(true)
					{
						AvailableFileAuthGroupDTO tmp = new AvailableFileAuthGroupDTO();
						tmp.setFileCode(rs.getString("file_code"));
						tmp.setGroupCode(rs.getString("group_code"));
						temp.add(tmp);
						if(rs.next()==false)
						{
							break;
						}
					}
				}
			});
		return temp;
	
	}
	
	public int deleteFileCode(String fileCode)
	{
		JdbcTemplate jt = getJdbcTemplate();
		String sql = "DELETE FROM available_file_auth_group_tb"
					+" WHERE file_code='" + fileCode + "'";
		System.out.println(sql);
		int res = jt.update(sql);
		
		return res;
	}
	
	public int deleteGroupCode(String groupCode)
	{
		JdbcTemplate jt = getJdbcTemplate();
		String sql = "DELETE FROM available_file_auth_group_tb"
					+" WHERE group_code='" + groupCode + "'";
		System.out.println(sql);
		int res = jt.update(sql);
		
		return res;
	
	}
	
	public int deleteFileCodeGroupCode(String fileCode, String groupCode)
	{
		JdbcTemplate jt = getJdbcTemplate();
		String sql = "DELETE FROM available_file_auth_group_tb"
					+" WHERE group_code='" + groupCode + "'"
					+" WHERE file_code='" + fileCode + "'";
		System.out.println(sql);
		int res = jt.update(sql);
		
		return res;
	
	}

	@Override
	public boolean insertAFAG(AvailableFileAuthGroupDTO dto) {
		// TODO Auto-generated method stub
		JdbcTemplate jt = getJdbcTemplate();
		String sql = "INSERT INTO available_file_auth_group_tb"
					+" VALUES ('" + dto.getFileCode() + "','"
					+dto.getGroupCode() + "')";
		System.out.println(sql);
		int res = jt.update(sql);
		if(res>0)
		{
			return true;
		}
		else
		{
			return false;
		}
		
	}
}
