//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileGroupVDAOImpl.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.daoimpl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;

import com.soloud.per.dao.BaseDAO;
import com.soloud.per.dao.FileGroupVDAO;
import com.soloud.per.dto.FileGroupVDTO;





public class FileGroupVDAOImpl extends BaseDAO implements FileGroupVDAO
{
	public List<FileGroupVDTO> searchFileGroup(String fileCode)
	{
		final List<FileGroupVDTO> temp = new ArrayList<FileGroupVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		String sql = "SELECT fi.file_code, gr.group_code, gr.group_name , gr.member_code" +
				" FROM file_tb fi, group_tb gr, available_file_auth_group_tb afag " +
				"WHERE fi.file_code = '" +fileCode+"' AND afag.file_code=fi.file_code" +
						" AND afag.group_code = gr.group_code";

		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					FileGroupVDTO tmp = new FileGroupVDTO();
					tmp.setFileCode(rs.getString("file_code"));
					tmp.setGroupCode(rs.getString("group_code"));
					tmp.setGroupName(rs.getString("group_name"));
					tmp.setMemberCode(rs.getString("member_code"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	
	public List<FileGroupVDTO> searchFileGroup()
	{
		final List<FileGroupVDTO> temp = new ArrayList<FileGroupVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT fi.file_code, gr.group_code, gr.group_name , gr.member_code" +
				" FROM file_tb fi, group_tb gr, available_file_auth_group_tb afag " +
				"WHERE afag.file_code=fi.file_code AND afag.group_code = gr.group_code";
		
		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					FileGroupVDTO tmp = new FileGroupVDTO();
					tmp.setFileCode(rs.getString("file_code"));
					tmp.setGroupCode(rs.getString("group_code"));
					tmp.setGroupName(rs.getString("group_name"));
					tmp.setMemberCode(rs.getString("member_code"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
}
