//
//

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GroupDAOImpl.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.daoimpl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;

import com.soloud.per.dao.BaseDAO;
import com.soloud.per.dao.GroupDeleteDAO;
import com.soloud.per.dao.GroupInsertDAO;
import com.soloud.per.dao.GroupSearchDAO;
import com.soloud.per.dao.GroupUpdateDAO;
import com.soloud.per.dto.GroupDTO;





public class GroupDAOImpl extends BaseDAO implements GroupSearchDAO, GroupInsertDAO, GroupDeleteDAO, GroupUpdateDAO
{
	public List<GroupDTO> searchAllGroup()
	{
		final List<GroupDTO> temp = new ArrayList<GroupDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM group_tb";
		
		
		jt.query(sql,new RowCallbackHandler() 
		{
			@Override
			public void processRow(ResultSet rs) throws SQLException 
			{
				//System.out.println(rs.getString("alarm_kind_code"));
				// TODO Auto-generated method stub
				while(true)
				{
					GroupDTO tmp = new GroupDTO();
					tmp.setGroupCode(rs.getString("group_code"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setGroupName(rs.getString("group_name"));
					temp.add(tmp);
					
					if(rs.next()==false)
					{
						break;
					}
				}
			}
		});
		return temp;
	}
	
	public GroupDTO searchGroupCode(String groupCode)
	{
		final List<GroupDTO> temp = new ArrayList<GroupDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM group_tb"
					+" WHERE group_code ='" + groupCode + "'";
		
		
		jt.query(sql,new RowCallbackHandler() 
		{
			@Override
			public void processRow(ResultSet rs) throws SQLException 
			{
				//System.out.println(rs.getString("alarm_kind_code"));
				// TODO Auto-generated method stub
				while(true)
				{
					GroupDTO tmp = new GroupDTO();
					tmp.setGroupCode(rs.getString("group_code"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setGroupName(rs.getString("group_name"));
					temp.add(tmp);
					
					if(rs.next()==false)
					{
						break;
					}
				}
			}
		});
		return temp.get(0);
	}
	
	public List<GroupDTO> searchMemberCode(String memberCode)
	{
		final List<GroupDTO> temp = new ArrayList<GroupDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM group_tb"
					+" WHERE member_code ='" + memberCode + "'";
		
		
		jt.query(sql,new RowCallbackHandler() 
		{
			@Override
			public void processRow(ResultSet rs) throws SQLException 
			{
				//System.out.println(rs.getString("alarm_kind_code"));
				// TODO Auto-generated method stub
				while(true)
				{
					GroupDTO tmp = new GroupDTO();
					tmp.setGroupCode(rs.getString("group_code"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setGroupName(rs.getString("group_name"));
					temp.add(tmp);
					
					if(rs.next()==false)
					{
						break;
					}
				}
			}
		});
		return temp;
	}
	
	public List<GroupDTO> searchGroupName(String groupName)
	{	
		final List<GroupDTO> temp = new ArrayList<GroupDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM group_tb"
					+" WHERE group_name='" + groupName + "'";
		
		
		jt.query(sql,new RowCallbackHandler() 
		{
			@Override
			public void processRow(ResultSet rs) throws SQLException 
			{
				//System.out.println(rs.getString("alarm_kind_code"));
				// TODO Auto-generated method stub
				while(true)
				{
					GroupDTO tmp = new GroupDTO();
					tmp.setGroupCode(rs.getString("group_code"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setGroupName(rs.getString("group_name"));
					temp.add(tmp);
					
					if(rs.next()==false)
					{
						break;
					}
				}
			}
		});
		return temp;
	}
	
	public GroupDTO searchMemberCodeGroupName(String memberCode, String groupName)
	{
		final List<GroupDTO> temp = new ArrayList<GroupDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM group_tb"
					+" WHERE member_code ='" + memberCode + "'"
					+" AND group_name = '" + groupName + "'";
		
		
		jt.query(sql,new RowCallbackHandler() 
		{
			@Override
			public void processRow(ResultSet rs) throws SQLException 
			{
				//System.out.println(rs.getString("alarm_kind_code"));
				// TODO Auto-generated method stub
				while(true)
				{
					GroupDTO tmp = new GroupDTO();
					tmp.setGroupCode(rs.getString("group_code"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setGroupName(rs.getString("group_name"));
					temp.add(tmp);
					
					if(rs.next()==false)
					{
						break;
					}
				}
			}
		});
		return temp.get(0);
	}
	
	public int updateGroupName(String groupCode, String groupName)
	{
		JdbcTemplate jt = getJdbcTemplate();
		
		final String sql = "UPDATE group_tb" 
		+" SET group_name="
		+"\'" + groupName + "\'"
		+" WHERE group_code="
		+"\'" + groupCode + "\'";

		int res = jt.update(sql);
		
		return res;
	}
	
	public boolean insertGroup(String memberCode, String groupName)
	{
		JdbcTemplate jt = getJdbcTemplate();
		
		final String sql = "INSERT INTO group_tb VALUES (" 
						 +" 'gr' || group_sequence.nextval," 
						 +" '"  + memberCode + "',"
						 +" '" + groupName + "')";


		int res = jt.update(sql);

		if(res>0)
		{
			return true;
		}
		else
		{
			return false;
		}
	}
	@Override
	public boolean insertGroupDTO(GroupDTO dto) {
		// TODO Auto-generated method stub
		JdbcTemplate jt = getJdbcTemplate();
		
		final String sql = "INSERT INTO group_tb VALUES (" 
						 +" '" + dto.getGroupCode() + "'," 
						 +" '"  + dto.getMemberCode() + "',"
						 +" '" + dto.getGroupName() + "')";


		int res = jt.update(sql);

		if(res>0)
		{
			return true;
		}
		else
		{
			return false;
		}
	}
	
	public int deleteGroupCode(String groupCode)
	{
		JdbcTemplate jt = getJdbcTemplate();
		
		String sql = "DELETE FROM group_tb WHERE group_code ='" + groupCode + "'";
					//+" AND is_read_alarm='" + isReadAlarm + "'";
		
		System.out.println(sql);
		int res = jt.update(sql);

		return res;
	}
	
	public int deleteMemberCode(String memberCode)
	{
		JdbcTemplate jt = getJdbcTemplate();
		
		String sql = "DELETE FROM group_tb WHERE member_code ='" + memberCode + "'";
					//+" AND is_read_alarm='" + isReadAlarm + "'";
		
		System.out.println(sql);
		int res = jt.update(sql);

		return res;
	}
	
	public int deleteGroupName(String groupName)
	{
		JdbcTemplate jt = getJdbcTemplate();
		
		String sql = "DELETE FROM group_tb WHERE group_name='" + groupName+ "'";
					//+" AND is_read_alarm='" + isReadAlarm + "'";
		
		System.out.println(sql);
		int res = jt.update(sql);

		return res;
	}

	
}
