//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MediaInfoDAOImpl.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.daoimpl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;

import com.soloud.per.dao.BaseDAO;
import com.soloud.per.dao.MediaInfoDeleteDAO;
import com.soloud.per.dao.MediaInfoInsertDAO;
import com.soloud.per.dao.MediaInfoSearchDAO;
import com.soloud.per.dao.MediaInfoUpdateDAO;
import com.soloud.per.dto.MediaInfoDTO;





public class MediaInfoDAOImpl extends BaseDAO implements MediaInfoUpdateDAO, MediaInfoInsertDAO, MediaInfoSearchDAO, MediaInfoDeleteDAO
{
	public List<MediaInfoDTO> searchAllMediaInfo()
	{
		final List<MediaInfoDTO> temp = new ArrayList<MediaInfoDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM media_info_tb";
		
		
		jt.query(sql,new RowCallbackHandler() 
		{
			@Override
			public void processRow(ResultSet rs) throws SQLException 
			{
				//System.out.println(rs.getString("alarm_kind_code"));
				// TODO Auto-generated method stub
				while(true)
				{
					//SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
					//String date= format.format(newArrivalDate.getTime()); // 20090529
					
					MediaInfoDTO tmp = new MediaInfoDTO();
					tmp.setMediaCode(rs.getString("media_code"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setFileCode(rs.getString("file_code"));
					tmp.setMediaSequence(rs.getInt("media_sequence"));
					temp.add(tmp);
					
					if(rs.next()==false)
					{
						break;
					}
				}
			}
		});
		return temp;
	}
	
	public MediaInfoDTO searchMediaCode(String mediaCode)
	{
		final List<MediaInfoDTO> temp = new ArrayList<MediaInfoDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM media_info_tb" 
					+" WHERE media_code = '" + mediaCode + "'";
		
		
		jt.query(sql,new RowCallbackHandler() 
		{
			@Override
			public void processRow(ResultSet rs) throws SQLException 
			{
				//System.out.println(rs.getString("alarm_kind_code"));
				// TODO Auto-generated method stub
				while(true)
				{
					//SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
					//String date= format.format(newArrivalDate.getTime()); // 20090529
					
					MediaInfoDTO tmp = new MediaInfoDTO();
					tmp.setMediaCode(rs.getString("media_code"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setFileCode(rs.getString("file_code"));
					tmp.setMediaSequence(rs.getInt("media_sequence"));
					temp.add(tmp);
					
					if(rs.next()==false)
					{
						break;
					}
				}
			}
		});
		return temp.get(0);
	}
	
	public List<MediaInfoDTO> searchMemberCode(String memberCode)
	{
		final List<MediaInfoDTO> temp = new ArrayList<MediaInfoDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM media_info_tb" 
					+" WHERE member_code = '" + memberCode + "'";
		
		
		jt.query(sql,new RowCallbackHandler() 
		{
			@Override
			public void processRow(ResultSet rs) throws SQLException 
			{
				//System.out.println(rs.getString("alarm_kind_code"));
				// TODO Auto-generated method stub
				while(true)
				{
					//SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
					//String date= format.format(newArrivalDate.getTime()); // 20090529
					
					MediaInfoDTO tmp = new MediaInfoDTO();
					tmp.setMediaCode(rs.getString("media_code"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setFileCode(rs.getString("file_code"));
					tmp.setMediaSequence(rs.getInt("media_sequence"));
					temp.add(tmp);
					
					if(rs.next()==false)
					{
						break;
					}
				}
			}
		});
		return temp;
	}
	
	public List<MediaInfoDTO> searchFileCode(String fileCode)
	{
		final List<MediaInfoDTO> temp = new ArrayList<MediaInfoDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM media_info_tb" 
					+" WHERE file_code = '" + fileCode + "'";
		
		
		jt.query(sql,new RowCallbackHandler() 
		{
			@Override
			public void processRow(ResultSet rs) throws SQLException 
			{
				//System.out.println(rs.getString("alarm_kind_code"));
				// TODO Auto-generated method stub
				while(true)
				{
					//SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
					//String date= format.format(newArrivalDate.getTime()); // 20090529
					
					MediaInfoDTO tmp = new MediaInfoDTO();
					tmp.setMediaCode(rs.getString("media_code"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setFileCode(rs.getString("file_code"));
					tmp.setMediaSequence(rs.getInt("media_sequence"));
					temp.add(tmp);
					
					if(rs.next()==false)
					{
						break;
					}
				}
			}
		});
		return temp;
	}
	
	public MediaInfoDTO searchMemberCodeFileCode(String memberCode, String fileCode)
	{
		final List<MediaInfoDTO> temp = new ArrayList<MediaInfoDTO>();

		JdbcTemplate jt = getJdbcTemplate();
		String sql = "SELECT * FROM media_info_tb" 
					+" WHERE member_code = '" + memberCode + "'"
					+" AND file_code = '" + fileCode + "'";
		
		
		jt.query(sql,new RowCallbackHandler() 
		{
			@Override
			public void processRow(ResultSet rs) throws SQLException 
			{
				//System.out.println(rs.getString("alarm_kind_code"));
				// TODO Auto-generated method stub
				while(true)
				{
					//SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
					//String date= format.format(newArrivalDate.getTime()); // 20090529
					
					MediaInfoDTO tmp = new MediaInfoDTO();
					tmp.setMediaCode(rs.getString("media_code"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setFileCode(rs.getString("file_code"));
					tmp.setMediaSequence(rs.getInt("media_sequence"));
					temp.add(tmp);
					
					if(rs.next()==false)
					{
						break;
					}
				}
			}
		});
		return temp.get(0);
	}
	
	public int updateMediaSequence(String mediaCode, int mediaSequence)
	{
		JdbcTemplate jt = getJdbcTemplate();
		String sql = "UPDATE media_info_tb" 
					+" SET media_sequence = " + mediaSequence
					+" WHERE meida_code = '" + mediaCode + "'";

		int res = jt.update(sql);
		return res;
	}
	
	public boolean insert(String memberCode, String fileCode, int mediaSequence)
	{
		JdbcTemplate jt = getJdbcTemplate();
		String sql = "INSERT INTO media_info_tb" 
					+" VALUES ( 'mi' || media_info_sequence.nextval ,"
					+"'" + memberCode + "',"
					+"'" + fileCode + "',"
					+ mediaSequence+ ")";

		int res = jt.update(sql);

		if(res>0)
		{
			return true;
		}
		else
		{
			return false;
		}
	}
	@Override
	public boolean insertMediaInfoDTO(MediaInfoDTO dto) {
		// TODO Auto-generated method stub
		JdbcTemplate jt = getJdbcTemplate();
		String sql = "INSERT INTO media_info_tb" 
					+" VALUES ('" + dto.getMediaCode() + "',"
					+"'" + dto.getMemberCode() + "',"
					+"'" + dto.getFileCode()+ "',"
					+ dto.getMediaSequence()+ ")";

		int res = jt.update(sql);

		if(res>0)
		{
			return true;
		}
		else
		{
			return false;
		}
	}
	
	public int deleteMediaCode(String mediaCode)
	{
		JdbcTemplate jt = getJdbcTemplate();
		
		String sql = "DELETE FROM media_info_tb WHERE media_code ='" + mediaCode + "'";
				
		
		System.out.println(sql);
		
		int res = jt.update(sql);

		return res;
	}
	public int deleteMemberCode(String memberCode)
	{
		JdbcTemplate jt = getJdbcTemplate();
		
		String sql = "DELETE FROM media_info_tb WHERE member_code ='" + memberCode + "'";
				
		System.out.println(sql);
		
		int res = jt.update(sql);

		return res;
	}
	
	public int deleteFileCode(String fileCode)
	{
		JdbcTemplate jt = getJdbcTemplate();
		
		String sql = "DELETE FROM media_info_tb WHERE file_code ='" + fileCode + "'";
				
		System.out.println(sql);
		
		int res = jt.update(sql);

		return res;
	}
	
	public int deleteMediaCodeMemberCode(String mediaCode, String memberCode)
	{
		JdbcTemplate jt = getJdbcTemplate();
		
		String sql = "DELETE FROM media_info_tb WHERE member_code ='" + memberCode + "'"
					+" AND media_code ='" + mediaCode +"'"; 
				
		System.out.println(sql);
		
		int res = jt.update(sql);

		return res;
	}
	
	public int deleteMediaCodeFileCode(String mediaCode, String fileCode)
	{
		JdbcTemplate jt = getJdbcTemplate();
		
		String sql = "DELETE FROM media_info_tb WHERE media_code ='" + mediaCode + "'"
					+" AND file_code ='" + fileCode +"'"; 
				
		System.out.println(sql);
		
		int res = jt.update(sql);

		return res;
	}

}
