//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberFolderVDAOImpl.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.daoimpl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;

import com.soloud.per.dao.BaseDAO;
import com.soloud.per.dao.MemberFolderVDAO;
import com.soloud.per.dto.MemberFolderVDTO;





public class MemberFolderVDAOImpl extends BaseDAO implements MemberFolderVDAO
{
	public List<MemberFolderVDTO> searchMemberFolder()
	{
		final List<MemberFolderVDTO> temp = new ArrayList<MemberFolderVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		String sql = "SELECT m.member_code, fo.folder_code , fo.folder_name , fo.parent_folder_code " +
				" FROM member_tb m, folder_tb fo" +
				" WHERE m.member_code = fo.member_code";


		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					MemberFolderVDTO tmp = new MemberFolderVDTO();
					tmp.setFolderCode(rs.getString("folder_code"));
					tmp.setFolderName(rs.getString("folder_name"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setParentFolderCode(rs.getString("parent_folder_code"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	
	public List<MemberFolderVDTO> searchMemberFolder(String memberCode)
	{
		final List<MemberFolderVDTO> temp = new ArrayList<MemberFolderVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		String sql = "SELECT m.member_code, fo.folder_code , fo.folder_name , fo.parent_folder_code " +
				" FROM member_tb m, folder_tb fo" +
				" WHERE m.member_code = '"+memberCode+"' AND m.member_code = fo.member_code";


		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					MemberFolderVDTO tmp = new MemberFolderVDTO();
					tmp.setFolderCode(rs.getString("folder_code"));
					tmp.setFolderName(rs.getString("folder_name"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setParentFolderCode(rs.getString("parent_folder_code"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
}
