//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberFileMediaVDAOImpl.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.daoimpl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;

import com.soloud.per.dao.BaseDAO;
import com.soloud.per.dao.MemberFileMediaVDAO;
import com.soloud.per.dto.MemberFileMediaVDTO;




public class MemberFileMediaVDAOImpl extends BaseDAO implements MemberFileMediaVDAO
{
	public List<MemberFileMediaVDTO> searchMemberFileMedia()
	{
		final List<MemberFileMediaVDTO> temp = new ArrayList<MemberFileMediaVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		String sql ="SELECT * FROM member_file_media_view";
		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					MemberFileMediaVDTO tmp = new MemberFileMediaVDTO();
					tmp.setFileCode(rs.getString("파일코드"));
					tmp.setFileName(rs.getString("파일이름"));
					tmp.setFileType(rs.getString("파일유형"));
					tmp.setMediaCode(rs.getString("미디어코드"));
					tmp.setMediaSequence(rs.getInt("미디어시퀀스"));
					tmp.setMemberCode(rs.getString("사용자코드"));
					tmp.setSize(rs.getInt("파일크기"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	
	public List<MemberFileMediaVDTO> searchMemberFileMedia(String memberCode)
	{
		final List<MemberFileMediaVDTO> temp = new ArrayList<MemberFileMediaVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		String sql ="SELECT * FROM member_file_media_view WHERE 사용자코드 = '"+memberCode+"'";
		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					MemberFileMediaVDTO tmp = new MemberFileMediaVDTO();
					tmp.setFileCode(rs.getString("파일코드"));
					tmp.setFileName(rs.getString("파일이름"));
					tmp.setFileType(rs.getString("파일유형"));
					tmp.setMediaCode(rs.getString("미디어코드"));
					tmp.setMediaSequence(rs.getInt("미디어시퀀스"));
					tmp.setMemberCode(rs.getString("사용자코드"));
					tmp.setSize(rs.getInt("파일크기"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
}
