//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberDAOImpl.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.daoimpl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;

import com.soloud.per.dao.BaseDAO;
import com.soloud.per.dao.MemberDeleteDAO;
import com.soloud.per.dao.MemberInsertDAO;
import com.soloud.per.dao.MemberSearchDAO;
import com.soloud.per.dao.MemberUpdateDAO;
import com.soloud.per.dto.MemberDTO;

public class MemberDAOImpl extends BaseDAO implements MemberSearchDAO, MemberInsertDAO, MemberDeleteDAO, MemberUpdateDAO
{
	public List<MemberDTO> searchAllMember(){
		final List<MemberDTO> temp = new ArrayList<MemberDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT * FROM member_tb";
		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					MemberDTO tmp = new MemberDTO();
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setMemberId(rs.getString("member_id"));
					tmp.setMemberKindCode(rs.getString("member_kind_code"));
					tmp.setMemberLimitCapacity(rs.getDouble("member_limit_capacity"));
					tmp.setName(rs.getString("member_name"));
					tmp.setPassword(rs.getString("member_password"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	public MemberDTO searchMemberCode(String memberCode)
	{
		final MemberDTO temp = new MemberDTO();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT * FROM member_tb WHERE member_code = '"+memberCode+"'";
		jdbcTemplate.query(sql,new RowCallbackHandler()	{
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					temp.setMemberCode(rs.getString("member_code"));
					temp.setMemberId(rs.getString("member_id"));
					temp.setMemberKindCode(rs.getString("member_kind_code"));
					temp.setMemberLimitCapacity(rs.getDouble("member_limit_capacity"));
					temp.setName(rs.getString("member_name"));
					temp.setPassword(rs.getString("member_password"));
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	public List<MemberDTO> searchMemberKindCode(String memberKindCode){
		final List<MemberDTO> temp = new ArrayList<MemberDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT * FROM member_tb WHERE member_kind_code = '"+memberKindCode+"'";
		jdbcTemplate.query(sql,new RowCallbackHandler()	{
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					MemberDTO tmp = new MemberDTO();
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setMemberId(rs.getString("member_id"));
					tmp.setMemberKindCode(rs.getString("member_kind_code"));
					tmp.setMemberLimitCapacity(rs.getDouble("member_limit_capacity"));
					tmp.setName(rs.getString("member_name"));
					tmp.setPassword(rs.getString("member_password"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	public MemberDTO searchMemberId(String memberId)
	{
		final MemberDTO temp = new MemberDTO();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT * FROM member_tb WHERE member_id = '"+memberId+"'";
		jdbcTemplate.query(sql,new RowCallbackHandler(){

			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					temp.setMemberCode(rs.getString("member_code"));
					temp.setMemberId(rs.getString("member_id"));
					temp.setMemberKindCode(rs.getString("member_kind_code"));
					temp.setMemberLimitCapacity(rs.getDouble("member_limit_capacity"));
					temp.setName(rs.getString("member_name"));
					temp.setPassword(rs.getString("member_password"));
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	public List<MemberDTO> searchMemberLimitCapacity(double memberLimitCapacity)
	{
		final List<MemberDTO> temp = new ArrayList<MemberDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT * FROM member_tb WHERE member_limit_capacity = '"+memberLimitCapacity+"'";
		jdbcTemplate.query(sql,new RowCallbackHandler()	{
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					MemberDTO tmp = new MemberDTO();
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setMemberId(rs.getString("member_id"));
					tmp.setMemberKindCode(rs.getString("member_kind_code"));
					tmp.setMemberLimitCapacity(rs.getDouble("member_limit_capacity"));
					tmp.setName(rs.getString("member_name"));
					tmp.setPassword(rs.getString("member_password"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	public List<MemberDTO> searchMemberName(String memberName)	{
		final List<MemberDTO> temp = new ArrayList<MemberDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT * FROM member_tb WHERE member_name LIKE '%"+memberName+"%'";
		jdbcTemplate.query(sql,new RowCallbackHandler()	{
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					MemberDTO tmp = new MemberDTO();
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setMemberId(rs.getString("member_id"));
					tmp.setMemberKindCode(rs.getString("member_kind_code"));
					tmp.setMemberLimitCapacity(rs.getDouble("member_limit_capacity"));
					tmp.setName(rs.getString("member_name"));
					tmp.setPassword(rs.getString("member_password"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	public MemberDTO searchMemberIdPwd(String memberId, String memberPwd)
	{
		final MemberDTO temp = new MemberDTO();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT * FROM member_tb WHERE member_id = '"+memberId+"' AND member_password = '"+memberPwd+"'";
		jdbcTemplate.query(sql,new RowCallbackHandler()	{
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					temp.setMemberCode(rs.getString("member_code"));
					temp.setMemberId(rs.getString("member_id"));
					temp.setMemberKindCode(rs.getString("member_kind_code"));
					temp.setMemberLimitCapacity(rs.getDouble("member_limit_capacity"));
					temp.setName(rs.getString("member_name"));
					temp.setPassword(rs.getString("member_password"));
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;	
	}
	public MemberDTO searchMemberIdName(String memberId, String memberName)
	{
		final MemberDTO temp = new MemberDTO();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT * FROM member_tb WHERE member_id = '"+memberId+"' AND member_name = '"+memberName+"'";
		jdbcTemplate.query(sql,new RowCallbackHandler()	{

			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					temp.setMemberCode(rs.getString("member_code"));
					temp.setMemberId(rs.getString("member_id"));
					temp.setMemberKindCode(rs.getString("member_kind_code"));
					temp.setMemberLimitCapacity(rs.getDouble("member_limit_capacity"));
					temp.setName(rs.getString("member_name"));
					temp.setPassword(rs.getString("member_password"));
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	public int updateMemberId(String memberCode, String newMemberId){
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "UPDATE member_tb SET member_id = '"+newMemberId+ "' WHERE member_code = '"+memberCode+"'";
		int res = jdbcTemplate.update(sql);
		return res;
	}
	public int updateMemberLimitCapacity(String memberCode, double newMemberLimitCapacity){
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "UPDATE member_tb SET member_limit_capacity = "+ newMemberLimitCapacity + " WHERE member_code = '"+memberCode+"'";
		int res = jdbcTemplate.update(sql);
		return res;
	}
	public int updateMemberName(String memberCode, String newMemberName){
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "UPDATE member_tb SET member_name = '"+newMemberName+ "' WHERE member_code = '"+memberCode+"'";
		int res = jdbcTemplate.update(sql);
		return res;
	}
	public int updateMemberName(String memberId, String memberPwd, String newMemberName)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "UPDATE member_tb SET member_name = '"+newMemberName+ "' WHERE member_id = '"+memberId+"' AND member_password= '"+memberPwd +"'";
		int res = jdbcTemplate.update(sql);
		return res;	
	}
	public int updateMemberPwd(String memberId, String memberPwd, String newMemberPwd)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "UPDATE member_tb SET member_password = '"+newMemberPwd+"' WHERE member_id = '"+memberId+"' AND member_password= '"+memberPwd +"'";
		int res = jdbcTemplate.update(sql);
		return res;
	}
	public int updateMemberLimitCapacity(String memberId, String memberPwd, double newMemberLimitCapacity)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "UPDATE member_tb SET member_limit_capacity = "+ newMemberLimitCapacity + " WHERE member_id = '"+memberId+"' AND member_password= '"+memberPwd +"'";
		int res = jdbcTemplate.update(sql);
		return res;
	}
	public int updateMemberId(String memberId, String memberPwd, String newMemberId)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "UPDATE member_tb SET member_id = '"+newMemberId+ "' WHERE member_id = '"+memberId+"' AND member_password= '"+memberPwd +"'";
		int res = jdbcTemplate.update(sql);
		return res;
	}
	public int updateMemberKindCode(String memberId, String memberPwd, String newMemberKindCode)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "UPDATE member_tb SET member_kind_code = '"+newMemberKindCode+ "' WHERE member_id = '"+memberId+"' AND member_password= '"+memberPwd +"'";
		int res = jdbcTemplate.update(sql);
		return res;
	}
	public boolean insertMember(String memberId, double memberLimitCapacity, String memberPwd, String memberName)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "INSERT INTO member_tb VALUES ( "+"'m'"+"  || member_sequence.NEXTVAL ,'mk1', ? , ?, ?, ?)";//¸â¹öÄÚµå,¸â¹öÀ¯ÇüÄÚµå,¸â¹ö¾ÆÀÌµð,¸â¹ö¿ë·®,¸â¹öºñ¹ø,¸â¹öÀÌ¸§

		Object[] params = new Object[]{memberId,memberLimitCapacity,memberPwd,memberName};
		int[] types = new int[]{Types.CHAR,Types.INTEGER,Types.VARCHAR,Types.VARCHAR};
		int res = jdbcTemplate.update(sql,params,types);
		if(res > 0)
			return true;
		else
			return false;
	}
	public int deleteMemberCode(String memberCode)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "DELETE FROM member_tb WHERE member_code = '"+memberCode+"'";
		int res = jdbcTemplate.update(sql);
		return res;
	}
	public int deleteMemberId(String memberId)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "DELETE FROM member_tb WHERE member_id = '"+memberId+"'";
		int res = jdbcTemplate.update(sql);
		return res;
	}
	public int deleteMemberIdPwd(String memberId, String memberPwd)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();

		String sql = "DELETE FROM member_tb WHERE member_id = '"+memberId+"' AND member_password = '"+memberPwd+"'";

		int res = jdbcTemplate.update(sql);
		return res;
	}
	public int updateMemberPwd(String memberCode, String newMemberPwd)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "UPDATE member_tb SET member_password = '"+newMemberPwd+"' WHERE member_code = '"+memberCode+"'";
		int res = jdbcTemplate.update(sql);
		return res;
	}
	@Override
	public boolean insertMebmberDTO(MemberDTO dto) {
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "INSERT INTO member_tb VALUES ( "+"'m'"+"  || member_sequence.NEXTVAL ,'mk1', ? , ?, ?, ?)";//¸â¹öÄÚµå,¸â¹öÀ¯ÇüÄÚµå,¸â¹ö¾ÆÀÌµð,¸â¹ö¿ë·®,¸â¹öºñ¹ø,¸â¹öÀÌ¸§

		Object[] params = new Object[]{dto.getMemberId(),dto.getMemberLimitCapacity(),dto.getPassword(),dto.getName()};
		int[] types = new int[]{Types.CHAR,Types.INTEGER,Types.VARCHAR,Types.VARCHAR};
		int res = jdbcTemplate.update(sql,params,types);
		if(res > 0)
			return true;
		else
			return false;
	}
	@Override
	public int updateMember(String memberId, String newName, String newPassword) {
		// TODO Auto-generated method stub
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "UPDATE member_tb SET member_name = '"+newName+ "'" + ", member_password='" + newPassword +"' "+ " WHERE member_id = '"+memberId+"'";
		int res = jdbcTemplate.update(sql);
		return res;	
	}
	@Override
	public String searchMemberAdmin(String memberId) {
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		String sql = "SELECT * FROM member_tb where member_id= '"+memberId+"'";
		final StringBuilder code = new StringBuilder("");
		jdbcTemplate.query(sql, new RowCallbackHandler(){
			
			public void processRow(ResultSet rs) throws SQLException{
				while(true){
					code.append(rs.getString("member_code"));
					if(rs.next() == false){
						break;
					}
				}
			}
		});
		return ""+code;
	}
}
