//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberFileVDAOImpl.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.daoimpl;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;

import com.soloud.per.dao.BaseDAO;
import com.soloud.per.dao.MemberFileVDAO;
import com.soloud.per.dto.MemberFileVDTO;




public class MemberFileVDAOImpl extends BaseDAO implements MemberFileVDAO
{
	public List<MemberFileVDTO> searchMemberFile(String memberCode)
	{
		final List<MemberFileVDTO> temp = new ArrayList<MemberFileVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		String sql = "SELECT * FROM member_file_view WHERE member_code='"+memberCode+"'";	
		System.out.println(sql);
	
		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					Date date = rs.getDate("file_latest_modifydate");
					long time = date.getTime();
					java.util.Date d = new java.util.Date(time);
					GregorianCalendar gc = new GregorianCalendar();
					gc.setTime(d);
					
					MemberFileVDTO tmp = new MemberFileVDTO();
					tmp.setFileCapacity(rs.getDouble("file_capacity"));
					tmp.setFileCode(rs.getString("file_code"));
					tmp.setFileComment(rs.getString("file_comment"));
					tmp.setFileLatestModifyDate(gc);
					tmp.setFileName(rs.getString("file_name"));
					tmp.setFileType(rs.getString("file_type"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setSize(rs.getInt("file_size"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;		
	}
	
	public List<MemberFileVDTO> searchMemberFile()
	{
		final List<MemberFileVDTO> temp = new ArrayList<MemberFileVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		String sql = "SELECT * FROM member_file_view";
		System.out.println(sql);
	
		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					Date date = rs.getDate("file_latest_modifydate");
					long time = date.getTime();
					java.util.Date d = new java.util.Date(time);
					GregorianCalendar gc = new GregorianCalendar();
					gc.setTime(d);
					
					MemberFileVDTO tmp = new MemberFileVDTO();
					tmp.setFileCapacity(rs.getDouble("file_capacity"));
					tmp.setFileCode(rs.getString("file_code"));
					tmp.setFileComment(rs.getString("file_comment"));
					tmp.setFileLatestModifyDate(gc);
					tmp.setFileName(rs.getString("file_name"));
					tmp.setFileType(rs.getString("file_type"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setSize(rs.getInt("file_size"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;	
	}
}
