//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberAlarmVDAOImpl.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.daoimpl;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;

import com.soloud.per.dao.BaseDAO;
import com.soloud.per.dao.MemberAlarmVDAO;
import com.soloud.per.dto.MemberAlarmVDTO;





public class MemberAlarmVDAOImpl extends BaseDAO implements MemberAlarmVDAO
{
	public List<MemberAlarmVDTO> searchMemberAlarm(String memberCode)
	{
		final List<MemberAlarmVDTO> temp = new ArrayList<MemberAlarmVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		String sql = "SELECT m.member_code,m.member_name, a.sender_code ,m2.member_name \"보내는이 \"  ,a.alarm_arrival_date,ak.alarm_kind_name , a.is_read_alarm " +
				" FROM member_tb m,member_tb m2,alarm_tb a,alarm_kind_tb ak" +
				" WHERE m.member_code = '"+memberCode+"' AND m.member_code = a.member_code AND a.alarm_kind_code = ak.alarm_kind_code AND a.sender_code = m2.member_code";

		System.out.println(sql);
		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					Date date = rs.getDate("alarm_arrival_date");
					long time = date.getTime();
					java.util.Date d = new java.util.Date(time);
					GregorianCalendar gc = new GregorianCalendar();
					gc.setTime(d);
					
					MemberAlarmVDTO tmp = new MemberAlarmVDTO();
					tmp.setAlarmArrivalDate(gc);
					tmp.setAlarmKindName(rs.getString("alarm_kind_name"));
					
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setMemberName(rs.getString("member_name"));
					tmp.setSenderCode(rs.getString("sender_code"));
					//tmp.setSenderName(rs.getString("보내는이"));
					tmp.setIsReadAlarm(rs.getString("is_read_alarm"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	
	public List<MemberAlarmVDTO> searchMemberAlarm()
	{
		final List<MemberAlarmVDTO> temp = new ArrayList<MemberAlarmVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		String sql = "SELECT m.member_code,m.member_name, a.sender_code ,m2.member_name \"보내는이 \"  ,a.alarm_arrival_date,ak.alarm_kind_name , a.is_read_alarm " +
				" FROM member_tb m,member_tb m2,alarm_tb a,alarm_kind_tb ak" +
				" WHERE m.member_code = a.member_code AND a.alarm_kind_code = ak.alarm_kind_code AND a.sender_code = m2.member_code";

		System.out.println(sql);
		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					Date date = rs.getDate("alarm_arrival_date");
					long time = date.getTime();
					java.util.Date d = new java.util.Date(time);
					GregorianCalendar gc = new GregorianCalendar();
					gc.setTime(d);
					
					MemberAlarmVDTO tmp = new MemberAlarmVDTO();
					tmp.setAlarmArrivalDate(gc);
					tmp.setAlarmKindName(rs.getString("alarm_kind_name"));
					
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setMemberName(rs.getString("member_name"));
					tmp.setSenderCode(rs.getString("sender_code"));
					//tmp.setSenderName(rs.getString("보내는이"));
					tmp.setIsReadAlarm(rs.getString("is_read_alarm"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;

	}
}
