//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberFriendVDAOImpl.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.daoimpl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;

import com.soloud.per.dao.BaseDAO;
import com.soloud.per.dao.MemberFriendVDAO;
import com.soloud.per.dto.MemberFriendVDTO;





public class MemberFriendVDAOImpl extends BaseDAO implements MemberFriendVDAO
{
	public List<MemberFriendVDTO> searchMemberFriend()
	{
		final List<MemberFriendVDTO> temp = new ArrayList<MemberFriendVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();

		String sql = "SELECT m.member_code ,m.member_name ,m2.member_code  , m2.member_name  " +
				" FROM member_tb m,member_tb m2, friend_tb fr" +
				" WHERE m.member_code = fr.member_code AND fr.friend_member_code = m2.member_code";

		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{	
					MemberFriendVDTO tmp = new MemberFriendVDTO();
					tmp.setFriendMemberCode(rs.getString("member_code"));
					tmp.setFriendMemberName(rs.getString("member_name"));
					tmp.setMemberCode(rs.getString("member_code"));
					tmp.setMemberName(rs.getString("member_name"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;

	}
	
	public List<MemberFriendVDTO> searchMemberFriend(String memberCode)
	{
		final List<MemberFriendVDTO> temp = new ArrayList<MemberFriendVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();

		String sql = "SELECT * FROM member_friend_view WHERE \"내코드\" = '"+memberCode+"'";
		
		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{						
					MemberFriendVDTO tmp = new MemberFriendVDTO();
					tmp.setFriendMemberCode(rs.getString("친구코드"));
					tmp.setFriendMemberName(rs.getString("친구이름"));
					tmp.setFriendMemberId(rs.getString("친구아이디"));
					tmp.setMemberCode(rs.getString("내코드"));
					tmp.setMemberName(rs.getString("내이름"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
}
