//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SharedFileVDAOImpl.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.daoimpl;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;

import com.soloud.per.dao.BaseDAO;
import com.soloud.per.dao.SharedFileVDAO;
import com.soloud.per.dto.SharedFileVDTO;




public class SharedFileVDAOImpl extends BaseDAO implements SharedFileVDAO
{
	public List<SharedFileVDTO> searchSharedFile(String sharedFolderCode)
	{

		final List<SharedFileVDTO> temp = new ArrayList<SharedFileVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT * FROM shared_file_view AND shared_folder_code='" + sharedFolderCode + "'";

		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					Date date = rs.getDate("file_latest_modifydate");
					long time = date.getTime();
					java.util.Date d = new java.util.Date(time);
					GregorianCalendar gc = new GregorianCalendar();
					gc.setTime(d);
					
					SharedFileVDTO tmp = new SharedFileVDTO();
					tmp.setFileCode(rs.getString("file_code"));
					tmp.setFileLatestModifydate(gc);
					tmp.setFileName(rs.getString("file_name"));
					tmp.setFileType(rs.getString("file_type"));
					tmp.setFolderCode(rs.getString("folder_code"));
					tmp.setSharedFolderCode(rs.getString("shared_folder_code"));
					tmp.setSize(rs.getInt("file_size"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;

	}
	
	public List<SharedFileVDTO> searchSharedFile()
	{
		final List<SharedFileVDTO> temp = new ArrayList<SharedFileVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT * FROM shared_file_view";

		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					Date date = rs.getDate("file_latest_modifydate");
					long time = date.getTime();
					java.util.Date d = new java.util.Date(time);
					GregorianCalendar gc = new GregorianCalendar();
					gc.setTime(d);
					
					SharedFileVDTO tmp = new SharedFileVDTO();
					tmp.setFileCode(rs.getString("file_code"));
					tmp.setFileLatestModifydate(gc);
					tmp.setFileName(rs.getString("file_name"));
					tmp.setFileType(rs.getString("file_type"));
					tmp.setFolderCode(rs.getString("folder_code"));
					tmp.setSharedFolderCode(rs.getString("shared_folder_code"));
					tmp.setSize(rs.getInt("file_size"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
}
