//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SharedFriendVDAOImpl.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.daoimpl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;

import com.soloud.per.dao.BaseDAO;
import com.soloud.per.dao.SharedFriendVDAO;
import com.soloud.per.dto.SharedFriendVDTO;




public class SharedFriendVDAOImpl extends BaseDAO implements SharedFriendVDAO
{
	@Override
	public List<SharedFriendVDTO> searchSharedFriend(String sharedFolderCode) {
		final List<SharedFriendVDTO> temp = new ArrayList<SharedFriendVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT * FROM shared_friend_view WHERE 공유폴더코드='" + sharedFolderCode + "'";
		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{

					SharedFriendVDTO tmp = new SharedFriendVDTO();
					tmp.setSharedFolderCode(rs.getString("공유폴더코드"));
					tmp.setMemberCode(rs.getString("멤버코드"));
					tmp.setMemberName(rs.getString("멤버이름"));
					tmp.setFriendCode(rs.getString("친구코드"));
					tmp.setFriendId(rs.getString("친구아이디"));
					tmp.setFriendName(rs.getString("친구이름"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;

	}
	public SharedFriendVDTO searchSharedFriend(String sharedFolderCode, String memberCode, String friendMemberCode) {
		final SharedFriendVDTO tmp = new SharedFriendVDTO();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		System.out.println("디비에서 받은 데이터 : "+sharedFolderCode+memberCode+friendMemberCode);

		String sql = "SELECT * FROM shared_friend_view WHERE 공유폴더코드='" + sharedFolderCode.trim() + "' AND 멤버코드='" + memberCode.trim() + "' AND 친구코드='"+friendMemberCode.trim()+"'";
		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					System.out.println("asd"+rs.getString("공유폴더코드"));
					System.out.println("asd"+rs.getString("멤버코드"));
					System.out.println("asd"+rs.getString("친구코드"));
					
					tmp.setSharedFolderCode(rs.getString("공유폴더코드"));
					tmp.setMemberCode(rs.getString("멤버코드"));
					tmp.setMemberName(rs.getString("멤버이름"));
					tmp.setFriendCode(rs.getString("친구코드"));
					tmp.setFriendId(rs.getString("친구아이디"));
					tmp.setFriendName(rs.getString("친구이름"));
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		System.out.println("디비에서 리턴직전 데이터 : "+tmp);
		return tmp;
	}
	
	public List<SharedFriendVDTO> searchSharedFriend()
	{
		final List<SharedFriendVDTO> temp = new ArrayList<SharedFriendVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();

		String sql = "SELECT * FROM shared_friend_view";
		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					
					SharedFriendVDTO tmp = new SharedFriendVDTO();
					tmp.setSharedFolderCode(rs.getString("공유폴더코드"));
					tmp.setMemberCode(rs.getString("멤버코드"));
					tmp.setMemberName(rs.getString("멤버이름"));
					tmp.setFriendCode(rs.getString("친구코드"));
					tmp.setFriendId(rs.getString("친구아이디"));
					tmp.setFriendName(rs.getString("친구이름"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	@Override
	public List<SharedFriendVDTO> searchSharedFriend(String sharedFolderCode,
			String memberCode) {
		final List<SharedFriendVDTO> temp = new ArrayList<SharedFriendVDTO>();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();

		String sql = "SELECT * FROM shared_friend_view WHERE 공유폴더코드='" + sharedFolderCode + "' AND '멤버코드'='" + memberCode + "'";
		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{

					SharedFriendVDTO tmp = new SharedFriendVDTO();
					tmp.setSharedFolderCode(rs.getString("공유폴더코드"));
					System.out.println("여긴어디냐면"+rs.getString("공유폴더코드"));
					tmp.setMemberCode(rs.getString("멤버코드"));
					tmp.setMemberName(rs.getString("멤버이름"));
					tmp.setFriendCode(rs.getString("친구코드"));
					tmp.setFriendId(rs.getString("친구아이디"));
					tmp.setFriendName(rs.getString("친구이름"));
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
}
