//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SharedFolderDAOImpl.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.daoimpl;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;

import com.soloud.per.dao.BaseDAO;
import com.soloud.per.dao.SharedFolderDeleteDAO;
import com.soloud.per.dao.SharedFolderInsertDAO;
import com.soloud.per.dao.SharedFolderSearchDAO;
import com.soloud.per.dao.SharedFolderUpdateDAO;
import com.soloud.per.dto.SharedFolderDTO;




public class SharedFolderDAOImpl extends BaseDAO implements SharedFolderSearchDAO, SharedFolderInsertDAO, SharedFolderDeleteDAO, SharedFolderUpdateDAO
{
	public List<SharedFolderDTO> searchAllSharedFolder()
	{
		final List<SharedFolderDTO> temp = new ArrayList<SharedFolderDTO>();
 
		
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT * FROM shared_folder_tb";
		jdbcTemplate.query(sql,new RowCallbackHandler(){
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					Date date = rs.getDate("shared_folder_makedate");
					
					long time = date.getTime();
					java.util.Date d = new java.util.Date(time);
					
					GregorianCalendar gc = new GregorianCalendar();
					gc.setTime(d);
					
					SharedFolderDTO tmp = new SharedFolderDTO();
					tmp.setFolderCode(rs.getString("folder_code"));
					tmp.setSharedFolderCode(rs.getString("shared_folder_code"));
					tmp.setSharedFolderMakeDate(gc);
					temp.add(tmp);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	
	public SharedFolderDTO searchSharedFolderCode(String sharedFolderCode)
	{
		final SharedFolderDTO temp = new SharedFolderDTO();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT * FROM shared_folder_tb WHERE shared_folder_code = '"+sharedFolderCode+"'";
		jdbcTemplate.query(sql,new RowCallbackHandler()	{
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					Date date = rs.getDate("shared_folder_makedate");
					
					long time = date.getTime();
					java.util.Date d = new java.util.Date(time);
					GregorianCalendar gc = new GregorianCalendar();
					gc.setTime(d);
					
					temp.setSharedFolderCode(rs.getString("shared_folder_code"));
					temp.setFolderCode(rs.getString("folder_code"));
					temp.setSharedFolderMakeDate(gc);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	
	public SharedFolderDTO searchFolderCode(String folderCode)
	{
		final SharedFolderDTO temp = new SharedFolderDTO();
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "SELECT * FROM shared_folder_tb WHERE folder_code = '"+folderCode+"'";
		jdbcTemplate.query(sql,new RowCallbackHandler()	{
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				while(true)
				{
					Date date = rs.getDate("shared_folder_makedate");
					
					long time = date.getTime();
					java.util.Date d = new java.util.Date(time);
					GregorianCalendar gc = new GregorianCalendar();
					gc.setTime(d);
					
					temp.setSharedFolderCode(rs.getString("shared_folder_code"));
					temp.setFolderCode(rs.getString("folder_code"));
					temp.setSharedFolderMakeDate(gc);
					if(rs.next() == false)
						break;
				}
			}
			
		});		
		return temp;
	}
	
	public int updateSharedFolderMakeDate(String sharedFolderCode, GregorianCalendar makeDate)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
		
		String date= format.format(makeDate.getTime()); // 20090529
		
		
		
		final String sql = "UPDATE shared_folder_tb" 
		+" SET shared_folder_makedate="
		+"\'" + date + "\'"
		+" WHERE shared_folder_code ="
		+"\'" + sharedFolderCode + "\'";

		int res = jdbcTemplate.update(sql);
		
		return res;
	}
	
	public boolean insertSharedFolder(String folderCode, GregorianCalendar makeDate)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		//SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY/MM/DD");
		//String str = dateFormat.format(makeDate.getTime());
		String sql = "INSERT INTO shared_folder_tb VALUES ("+"'sf'"+"  || shared_folder_sequence.NEXTVAL, ? ,SYSDATE)";//¸â¹öÄÚµå,¸â¹öÀ¯ÇüÄÚµå,¸â¹ö¾ÆÀÌµð,¸â¹ö¿ë·®,¸â¹öºñ¹ø,¸â¹öÀÌ¸§
		
		Object[] params = new Object[]{folderCode};
		int[] types = new int[]{Types.CHAR};
		int res = jdbcTemplate.update(sql,params,types);
		if(res > 0)
			return true;
		else
			return false;
	}
	
	public int deleteSharedFolderCode(String sharedFolderCode)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "DELETE FROM shared_folder_tb WHERE shared_folder_code = '"+sharedFolderCode+"'";
		int res = jdbcTemplate.update(sql);
		return res;
	}
	
	public int deleteFolderCode(String folderCode)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		String sql = "DELETE FROM shared_folder_tb WHERE folder_code = '"+folderCode+"'";
		int res = jdbcTemplate.update(sql);
		return res;
	}
	
	public int deleteSharedFolderMakeDate(GregorianCalendar startDate, GregorianCalendar endDate)
	{
		JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
		String start= format.format(startDate.getTime()); //
		String end= format.format(endDate.getTime()); // 
		
		String sql = "DELETE FROM shared_folder_tb WHERE shared_folder_makedate > '" + start+ "'"+" AND shared_folder_makedate < '" + end + "'";
		int res = jdbcTemplate.update(sql);
		return res;
	}

	@Override
	public boolean insertSharedFolderDTO(SharedFolderDTO dto) {
JdbcTemplate jdbcTemplate = getJdbcTemplate();
		
		//SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY/MM/DD");
		//String str = dateFormat.format(makeDate.getTime());
		String sql = "INSERT INTO shared_folder_tb VALUES ("+"'sf'"+"  || shared_folder_sequence.NEXTVAL, ? ,SYSDATE)";//¸â¹öÄÚµå,¸â¹öÀ¯ÇüÄÚµå,¸â¹ö¾ÆÀÌµð,¸â¹ö¿ë·®,¸â¹öºñ¹ø,¸â¹öÀÌ¸§
		
		Object[] params = new Object[]{dto.getFolderCode()};
		int[] types = new int[]{Types.CHAR};
		int res = jdbcTemplate.update(sql,params,types);
		if(res > 0)
			return true;
		else
			return false;
	}
}
