//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AlarmKindInsertDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import com.soloud.per.dto.AlarmKindDTO;
/**
 * 알람유형의 데이터를 추가하는 인터체이스
 * @author 장성봉 <hr>
 * 알람유형  DataBase에 지정한 데이터를  가지는 알람유형 record를 추가하는 인터페이스
 */
public interface AlarmKindInsertDAO
{
	/**
	 * 알람유형 DataBase에 지정한 알람유형이름을 가지는 Record를 추가하는 메소드
	 * @param alarmKindName 알람유형<br>
	 * 가능항 알람유형 : 친구신청, 태그, 리빙룸초대, 친구수락
	 * @return 성공적으로 추가한 경우 - true
	 */
	public boolean insertAlarmKind(String alarmKindName);
	/**
	 * 알람유형 DataBase에 지정한 AlarmKindDTO정보를 가지는 알람유형데이터를 추가하는 메소드
	 * @param dto AalarmKindDTO 타입의 인스턴스 객체
	 * @return 성공적으로 추가한 경우  - true
	 */
	public boolean insertAlarmKindDTO(AlarmKindDTO dto);
}
