//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AlarmInsertDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import com.soloud.per.dto.AlarmDTO;
/**
 * 알람데이터를 추가하는 인터페이스
 * @author 장성봉<hr> 
 * 알람 DataBase에 지정한 데이터를 가지는 알람 Record를 추가하는 인터페이스
 */
public interface  AlarmInsertDAO
{
	/**
	 * 알람데이터베이스에 알람종류,멤버코드,보낸사람멤보코드정보를 가지는 알람 Record를 추가하는 메소드
	 * @param alarmKindCode 알람유형
	 * @param memberCode 받는사람멤버코드
	 * @param SenderCode 보낸사람멤버코드
	 * @return 성공적으로 추가한 경우 true
	 */
	public boolean insertAlarm(String alarmKindCode, String memberCode, String SenderCode);
	/**
	 * 알람데이터베이스에 지정한 AlarmDTO정보를 가지는 알람데이터를 추가하는 메소드
	 * @param dto 알람코드,알람유형,보낸사람멤버코드,확인여부를 캡슐화한 AlarmDTO클래스
	 * @return 성공적으로 추가한 경우 true
	 */
	public boolean insertAlarmDTO(AlarmDTO dto);
}
