//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AlarmDeleteDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.GregorianCalendar;
/**
 * 알람데이터를 삭제하는 인터페이스
 * @author 장성봉 <hr>
 * 알람 DataBase에서 지정한 데이터를 가지는 Record를 삭제하는 인터페이스
 */
public interface AlarmDeleteDAO
{
	/**
	 * 알람데이터 베이스에서 지정한 알람코드에 해당하는 알람데이터 삭제하는 메소드
	 * @param alarmCode 알람코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteAlarmCode(String alarmCode);
	/**
	 * 알람데이터 베이스에서 지정한 회원코드에 해당하는 알람데이터 삭제하는 메소드
	 * @param memberCode 멤버코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteMemberCode(String memberCode);
	/**
	 * 알람데이터 베이스에서 지정한 특정 기간에 해당하는 알람데이터 삭제하는 메소드
	 * @param memberCode 멤버코드
	 * @param startDate 시작일
	 * @param endDate 마지막일
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteAlarmArrivalDate(String memberCode, GregorianCalendar startDate, GregorianCalendar endDate);
	/**
	 * 알람데이터 베이스에서 지정한 특정 보낸이와 받는이정보에 해당하는 알람데이터 삭제하는 메소드
	 * @param memberCode 받는멤버코드
	 * @param senderCode 보낸멤버코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteAlarmMemberSenderCode(String memberCode, String senderCode);
	/**
	 * 알람데이터 베이스에서 지정한 확인여부에 해당하는 알람데이터 삭제하는 메소드
	 * @param memberCode 멤버코드
	 * @param isReadAlarm 확인여부
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteAlarmMemberIsReadAlarm(String memberCode, String isReadAlarm);
}
