//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AlarmKindUpdateDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 알람유형의 데이터를 변경하는 인터체이스
 * @author 장성봉<hr>
 * 알람유형 DataBase에 지정한 데이터을 가지는 <br>
 * Record의 데이터를 지정한 데이터로 변경하는 인터페이스
 */
public interface AlarmKindUpdateDAO
{
	/**
	 * 알람유형 DataBase에 지정한 알람유형코드를 가지는 Record의<br>
	 * 알람유형이름을 변경하는 메소드
	 * @param alarmKindCode 알람코드
	 * @param alarmKindName 변경할 알람유형이름
	 * 가능항 알람유형 : 친구신청, 태그, 리빙룸초대, 친구수락
	 * @return 성공적으로 변경한 행의 개수
	 */
	public int updatedAlarmKindName(String alarmKindCode, String alarmKindName);
}
