//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AlarmKindDeleteDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 알람유형데이터를 삭제하는 인터페이스
 * @author 장성봉 <hr>
 * 알람유형 DataBase에서 지정한 데이터를 가지는 record를 변경하는 인터페이스<br>
 * 이 인터페이스를 사용하여 알람유형 record를 삭제하면 알람데이터베이스 record 삭제 트리거가 발생한다.
 */
public interface AlarmKindDeleteDAO
{
	/**
	 * 알람유형 DataBase에서 지정한 알람코드에 해당하는 Record 삭제 메소드<br>
	 * 이 메소드 호출시 트리거가 작동<br>
	 * 삭제 알람 유형 데이터를 알람데이터베이스에서 모두 삭제
	 * @param alarmKindCode 삭제할알람유형
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteAlarmKindCode(String alarmKindCode);
	/**
	 * 알람유형 DataBase에서 지정한 알람유형에 해당하는 Record 삭제<br>
	 * 이 메소드 호출시 트리거가 작동<br>
	 * 삭제 알람 유형 데이터를 알람데이터베이스에서 모두 삭제
	 * @param alarmKindName 삭제할알람유형
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteAlarmKindName(String alarmKindName);
}
