//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AlarmUpdateDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//


package com.soloud.per.dao;
import java.util.GregorianCalendar;


public interface AlarmUpdateDAO
{
	public int updateAlarmArrivalDate(String alarmCode, GregorianCalendar newArrivalDate);
	public int updateAlarmIsRead(String alarmCode);
	public int updateAlarmKind(String alarmCode, String alarmKindCode);
}
