//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AlarmKindSearchDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.List;

import com.soloud.per.dto.AlarmKindDTO;
/**
 * 알람유형의 데이터를 조회하는 인터페이스
 * @author 장성봉 <hr>
 * 알람유형 DataBase에 지정한 데이터를 가지는  Record를 조회한는 인터페이스
 */
public interface AlarmKindSearchDAO
{
	/**
	 *  알람유형 DataBase의 모든 데이터를 조회하는 메소드
	 * @return AlarmKindDTO타입의 List 객체 
	 */
	public List<AlarmKindDTO> searchAllAlarmKind();
	/**
	 * 알람유형 DataBase에 지정한 알람코드를 가지는 모든 알람유형 Record를 조회하는 메소드
	 * @param alarmKindCode 알람코드
	 * @return 지정한 알람코드를 가지는 AlarmKindDTO타입의  객체
	 */
	public AlarmKindDTO searchAlarmKindCode(String alarmKindCode);
	/**
	 * 알람유형 DataBase에 지정한 알람유형이름을 가지는 모든 알람유형 Record를 조회하는 메소드
	 * @param alarmKindName 알람유형이름<br>
	 * 가능항 알람유형 : 친구신청, 태그, 리빙룸초대, 친구수락
	 * @return 지정한 알람유형이름을 가지는 AlarmKindDTO타입의 List 객체 
	 */
	public List<AlarmKindDTO> searchAlarmKindName(String alarmKindName);
}
