//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AvailableFolderAuthFriendDeleteDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 공유폴더친구 데이터를 삭제하는 인터페이스
 * @author 장성봉<hr>
 * 공유폴더친구 데이터베이스에서 지정한 데이터를 가지는<br>
 * Record를 삭제하는 인터페이스
 */
public interface AvailableFolderFriendDeleteDAO
{
	/**
	 * 공유폴더친구 데이터베이스에서 지정한 친구코드를 가지는 공유폴더친구데이터를 삭제하는 메소드
	 * @param friendCode 친구코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteFriendCode(String friendCode);
	/**
	 * 공유폴더친구 데이터베이스에서 지정한 공유폴더코드를 가지는 공유폴더친구데이터를 삭제하는 메소드
	 * @param sharedFolderCode 공유폴더코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteSharedFolderCode(String sharedFolderCode);
	/**
	 * 공유폴더친구 데이터베이스에서 지정한 친구코드와 공유폴더코드를 가지는 공유폴더친구데이터를 삭제하는 메소드
	 * @param friendCode 친구코드
	 * @param sharedCode 공유폴더코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteFriendCodeSharedCode(String friendCode, String sharedCode);
}
