//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AvailableFolderAuthFriendUpdateDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 공유폴더친구 데이터를 변경하는 인터페이스
 * @author 장성봉<br>
 * 공유폴더친구 데이터베이스에서 지정한 데이터를 가지는<br>
 * Record를 지정한 데이터로 변경하는 인터페이스
 */
public interface AvailableFolderFriendUpdateDAO
{
}
