//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AvailableFolderAuthFriendSearchDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.List;

import com.soloud.per.dto.*;
/**
 * 공유폴더친구 데이터를 조회하는 인터페이스
 * @author 장성봉 <hr>
 * 공유폴더친구 데이터베이스에서 지정한 데이터를 가지는<br>
 * Record를 조회하는 인터페이스
 */
public interface AvailableFolderFriendSearchDAO
{
	/**
	 * 공유폴더친구 데이터베이스에서 모든 공유폴더친구 Record를 조회하는 메소드
	 * @return AvailableFolderFriendDTO타입의 List 객체
	 */
	public List<AvailableFolderFriendDTO> searchAllAFAF();
	/**
	 * 공유폴더친구 데이터베이스에서 지정한 친구코드를 가지는 공유폴더친구 Record를 조회하는 메소드
	 * @param friendCode 친구코드 
	 * @return AvailableFolderFriendDTO타입의 List 객체
	 */
	public List<AvailableFolderFriendDTO> searchFriendCode(String friendCode);
	/**
	 * 공유폴더친구 데이터베이스에서 지정한 공유폴더코드를 가지는 공유폴더친구 Record를 조회하는 메소드
	 * @param sharedFolderCode 공유폴더 코드
	 * @return AvailableFolderFriendDTO타입의 List 객체
	 */
	public List<AvailableFolderFriendDTO> searchSharedFolderCode(String sharedFolderCode);
}
