//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AvailableFileAuthGroupSearchDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.List;

import com.soloud.per.dto.AvailableFileAuthGroupDTO;

/**
 * 사용가능한파일그룹 데이터를 조회하는 인터페이스
 * @author 장성봉<br>
 * 사용가능한파일그룹 데이터베이스에서 지정한 데이터를 가지는 <br>
 * Record를 조회하는 인터페이스
 */
public interface AvailableFileAuthGroupSearchDAO
{
	/**
	 * 사용가능한파일그룹 데이터베이스에서 모든 사용가능한파일그룹 Record를 조회하는 메소드
	 * @return AvailableFileAuthGroupDTO타입의 List 객체
	 */
	public List<AvailableFileAuthGroupDTO> searchAllAFAG();
	/**
	 * 사용가능한파일그룹 데이터베이스에서 지정한 파일코드를 가지는 사용가능한파일그룹 Record를 조회하는 메소드
	 * @param fileCode 파일코드
	 * @return AvailableFileAuthGroupDTO타입의 List 객체
	 */
	public List<AvailableFileAuthGroupDTO> searchFileCode(String fileCode);
	/**
	 * 사용가능한파일그룹 데이터베이스에서 지정한 그룹코드를 가지는 사용가능한파일그룹 Record를 조회하는 메소드
	 * @param groupCode 그룹코드
	 * @return AvailableFileAuthGroupDTO타입의 List 객체
	 */
	public List<AvailableFileAuthGroupDTO> searchGroupCode(String groupCode);
}
