//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AvailableFileAuthGroupUpdateDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 사용가능한파일그룹 데이터를 변경하는 인터페이스
 * @author 장성봉<hr>
 * 사용가능한파일그룹 DataBase에  지정한 데이터를 가지는 <br>
 * Record의 데이터를 지정한 데이토 변경하는 인터페이스
 */
public interface AvailableFileAuthGroupUpdateDAO
{
}
