//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BaseDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
/**
 * 모든 DAO클래스의 기본 구현을 제공한다.
 * @author 장성봉<hr>
 * 
 */
public abstract class BaseDAO implements DAO
{
	private DataSourceTransactionManager transactionManager;
	private JdbcTemplate jdbcTemplate;
	public void setTransactionManager(DataSourceTransactionManager transactionManager)
	{
		this.transactionManager=transactionManager;
		init();
	}
	private synchronized void init()
	{
		this.jdbcTemplate=new JdbcTemplate(this.transactionManager.getDataSource());
	}
	
	protected synchronized JdbcTemplate getJdbcTemplate()
	{
		return jdbcTemplate;
	}
}
