//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
/**
 * DAO 인터페이스는 모든 DAO인터페이스의 상위 인터페이스 이다.
 * @author 장성봉 <hr>
 *
 */
public interface DAO
{
	/**
	 * DataSourceTransactionManager 멤버필드를 초기화 하는 메소드
	 * @param transactionManager DataSourceTransactionManager객체
	 */
	public void setTransactionManager(DataSourceTransactionManager transactionManager);
}
