//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileUpdateDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;//
import java.util.GregorianCalendar;
/**
 * 파일 데이터를 변경하는 인터페이스
 * @author 장성봉 <hr>
 * 파일 데이터베이스에서 지정한 데이터를 가지는 <br>
 * Record를 지정한 데이터로 변경하는 인터페이스
 */
public interface FileUpdateDAO
{
	/**
	 * 파일데이터베이스에서 지정한 파일코드 데이터를 가지는 <br>
	 * Record를 마지막 수정일을 지정한 데이터로 수정하는 메소드
	 * @param fileCode 파일코드
	 * @param latestModifyDate 마지막 수정일
	 * @return 성공적으로 변경한 행의 갱수
	 */
	public int updateFileCodeLatestModifyDate(String fileCode, GregorianCalendar latestModifyDate);
	/**
	 * 파일데이터베이스에서 지정한 파일코드 데이터를 가지는 <br>
	 * Record를 파일코멘트 데이터를 지정한 데이터로 수정하는 메소드
	 * @param fileCode 파일코드
	 * @param fileComment 파일코멘트
	 * @return 성공적으로 변경한 행의 개수
	 */
	public int updateFileCodeFileComment(String fileCode, String fileComment);
	/**
	 * 파일데이터베이스에서 지정한 파일코드 데이터를 가지는 <br>
	 * Record를 파일이름을 지정한 데이터로 수정하는 메소드
	 * @param fileCode 파일코드
	 * @param fileName 파일이름
	 * @return 성공적으로 변경한 행의 갱수
	 */
	public int updateFileCodeFileName(String fileCode, String fileName);
	/**
	 * 파일데이터베이스에서 지정한 파일코드 데이터를 가지는 <br>
	 * Record를 공유파일여부를 지정한 데이터로 수정하는 메소드
	 * @param fileCode 파일코드
	 * @param fileIsShared 공유파일 여부
	 * 공유파일여부 : "공유" 아닌경우 : "일반"
	 * @return 성공적으로 변경한 행의 갱수
	 */
	public int updateFileCodeFileIsShared(String fileCode, String fileIsShared);
	/**
	 * 파일데이터베이스에서 지정한 파일코드 데이터를 가지는 <br>
	 * Record를 폴더코드를 지정한 폴더코드 데이터로 수정하는 메소드
	 * @param fileCode 파일코드
	 * @param newFolderCode 변경 할 폴더 코드
	 * @return 성공적으로 변경한 행의 개수
	 */
	public int updateFileCodeFolderCode(String fileCode,String newFolderCode);
}
