//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileGroupVDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;//
import java.util.List;

import com.soloud.per.dto.FileGroupVDTO;
/**
 * 파일코드로 그룹의 정보를 조회하는  VIEW 인터페이스
 * @author 장성봉<hr>
 * 파일데이터베이스와 그룹데이터베이스에서 지정한 데이터를 가지는 <br>
 * Record의 파일코드,파일접근가능그룹코드,그룹이름,그룹에속한멤버코드를 조회하는 인터페이스
 */
public interface FileGroupVDAO
{
	/**
	 * 파일데이터베이스와 그룹 데이터베이스에서 지정한 파일코드 데이터를 가지는 <br>
	 * Record를 조회하는 메소드<br>
	 * @param fileCode 파일코드
	 * @return 조회한 일코드,파일접근가능그룹코드,그룹이름,그룹에속한멤버코드를 캡슐화 하고 있는 FileGroupVDTO 객체
	 */
	public List<FileGroupVDTO> searchFileGroup(String fileCode);
	/**
	 * 파일데이터베이스와 그룹 데이터베이스에서 모든 Record를 조회하는 메소드<br>
	 * @return 조회한 일코드,파일접근가능그룹코드,그룹이름,그룹에속한멤버코드를 캡슐화 하고 있는 FileGroupVDTO 객체
	 */
	public List<FileGroupVDTO> searchFileGroup();
}
