package com.soloud.per.dao;

import java.util.GregorianCalendar;
import java.util.List;

import com.soloud.per.dto.FileDTO;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileSearchDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//




public interface FileSearchDAO
{
	public List<FileDTO> searchAllFile();
	
	public FileDTO searchFileCode(String fileCode);
	
	public List<FileDTO> searchMemberCode(String memberCode);
	
	public List<FileDTO> searchFolderCode(String folderCode);
	
	public List<FileDTO> searchFileLatestModifyDate(GregorianCalendar startDate, GregorianCalendar endDate);
	
	public List<FileDTO> searchFileType(String fileType);
	
	public List<FileDTO> searchFileName(String fileName);
	
	public List<FileDTO> searchIsSharedFile(String isSharedFile);
	
	public List<FileDTO> searchFileNameMemberCode(String fileName, String memberCode);
	
	public List<FileDTO> searchFileNameFileType(String fileName, String fileType);
	
	public List<FileDTO> searchFileNameIsSharedFile(String fileName, String isSharedFile);
	
	public List<FileDTO> searchMemberCodeIsSharedFile(String memberCode, String isSharedFile);
	
	public List<FileDTO> searchMemberCodeFileType(String memberCode, String fileType);

	public List<FileDTO> searchMemberFileTypeName(String fileType, String fileName);
	
	public List<FileDTO> searchMemberCodeFolderLatestModifyDate(String memberCode, GregorianCalendar startDate, GregorianCalendar endDate);
	
	public List<FileDTO> searchMemberCodeFileName(String memberCode, String fileName);

	public List<FileDTO> searchMemberCodeFolderCode(String memberCode, String folderCode);
	
	
}
