//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileBinaryUpdateDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 파일바이너리 데이터를 변경하는 인터페이스
 * @author 장성봉<hr>
 * 파일 바이너리 데이터베이스에서 지정한 데이터를 가지는 <br>
 * Record를 지정한 데이터로 변경하는 인터페이스
 */
public interface FileBinaryUpdateDAO
{
	/**
	 * 파일바이너리 데이터베이스에서 지정한 파일코드 데이터를 가지는 Record를 지정한 파일바이너리 데이터롤 변경하는 메소드
	 * @param fileCode 파일코드
	 * @param newFileBinary 변경할 파일바이너리 객체
	 * @return 성공적으로 변경한 행의 개수
	 */
	public int updateFileBinary(String fileCode, Object newFileBinary);
}
