//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileBinaryInsertDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import com.soloud.per.dto.FileBinaryDTO;
/**
 * 파일바이너리데이터를 추가하는 인터페이스
 * @author 장성봉 <hr>
 * 파일바이너리 데이터베이스에서 지정한 데이터를 가지는 <br>
 * Record에 추가하는 인터페이스
 */
public interface FileBinaryInsertDAO
{
	/**
	 * 파일바이너리 데이터베이스에 지정한 파일코드,파일바이너리, 파일크기값을 가지는 데이터를 추가하는 메소드
	 * @param fileCode 파일코드
	 * @param fileBinary 파일바이너리
	 * @param size 파일크기
	 * @return 성공적으로 추가한 경우 - true
	 */
	public boolean insertFileBinary(String fileCode, Object fileBinary, int size);
	/**
	 * 파일바이너리데이터베이스에 지정한 데이터를 가지는 FileBinaryDTO 객체를 추가하는 메소드
	 * @param dto 지정할 데이터를 캡슐화 하고 있는 FileBinaryDTO 객체
	 * @return 성공적으로 추가한 경우 - true
	 */
	public boolean insertFileBinaryDTO(FileBinaryDTO dto);
}
