//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileBinarySearchDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.List;

import com.soloud.per.dto.FileBinaryDTO;
/**
 * 파일바이너리데이터를 조회하는 인터페이스
 * @author 장성봉<hr>
 * 파일바이너리 데이터베이스에서 지정한 데이터를 가지는 <br>
 * Record를 조회하는 인터페이스
 */
public interface FileBinarySearchDAO
{
	/**
	 * 파일바이너리 데이터베이스의 모든 Record를 조회하는 메소드
	 * @return FileBinayDTO타입의 List
	 */
	public List<FileBinaryDTO> selectAllFileBinary();
	/**
	 * 파일바이너리 데이터베이스에서 지정한 파일코드 데이터를 가지는 ReCord를 조회하는 메소드
	 * @param fileCode 파일코드
	 * @return FileBinaryDTO 타입의 객체
	 */
	public FileBinaryDTO selectFileBinary(String fileCode);
	/**
	 * 파일바이너리 데이터베이스에서 지정한 파일바이너리코드 데이터를 가지는 Record를 조회하는 메소드
	 * @param fileBinaryCode 파일바이너리코드
	 * @return FileBinary 타입의 객체
	 */
	public FileBinaryDTO selectFileBinaryCode(String fileBinaryCode);
}
