//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileInsertDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;//
import java.util.GregorianCalendar;

import com.soloud.per.dto.FileDTO;
/**
 * 파일 데이터를 추가하는 인터페이스
 * @author 장성봉<hr>
 * 파일 데이터베이스에 지정한 데이터를 추가하는 인터페이스
 */
public interface FileInsertDAO
{
	/**
	 * 파일 데이터베이스에 지정한 멤버코드, 폴더코드, 마지막수정일, 파일코멘트, 파일유형, 파일크기, 파일이름, 공유파일여부 데이터를 가지는<br>
	 * 데이터를 추가하는 메소드
	 * @param memberCode 멤버코드
	 * @param folderCode 폴더코드
	 * @param latestModifyDate 마지막수정일
	 * @param fileComment 파일코멘트
	 * @param fileType 파일유형
	 * @param fileCapacity 파일크기
	 * @param fileName 파일이름
	 * @param isSharedFile 공유파일여부
	 * @return 성공적으로 추가한 경우 -true
	 */
	public boolean insert(String memberCode, String folderCode, GregorianCalendar latestModifyDate, String fileComment, String fileType, double fileCapacity, String fileName, String isSharedFile);
	/**
	 * 파일 데이터베이스에서 지정한 데이터를 캡슐화한 FileDTO 객체를 추가하는 메소드
	 * @param dto FileDTO객체
	 * @return 성공적으로 추가한 경우 - true
	 */
	public boolean insert(FileDTO dto);
}
