//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileBinaryDeleteDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 파일바이너리 데이터를 삭제하는 인터페이스
 * @author 장성봉<hr>
 * 파일바이너리데이터베이스의 지정한 데이터를 가지는<br>
 * Record를 삭제하는 인터페이스
 */
public interface FileBinaryDeleteDAO
{
	/**
	 * 파일바이너리 데이터베이스에서 지정한 파일바이너리코드를 가지는 파일바이너리 Record를 삭제하는 메소드
	 * @param fileBinaryCode 파일바이너리코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteFileBinaryCode(String fileBinaryCode);
	/**
	 * 파일바이너리 데이터베이스에서 지정한 파일코드를 가지는 파일바이너리 Record를 삭제하는 메소드
	 * @param fileCode 파일코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteFileCode(String fileCode);
}
