
package com.soloud.per.dao;//

import java.util.List;

import com.soloud.per.dto.FolderDTO;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FolderSearchDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//




public interface FolderSearchDAO
{
	public List<FolderDTO> searchAllFolder();
	
	public FolderDTO searchFolderCode(String folderCode);
	
	public List<FolderDTO> searchMemberCode(String memberCode);
	
	public List<FolderDTO> searchFolderParentCode(String parentFolderCode);
	
	public List<FolderDTO> searchFolderName(String folderName);
	
	public List<FolderDTO> searchIsSharedFolder(String isSharedFolder);
	
	public List<FolderDTO> searchMemberCodeFolderName(String memberCode, String folderName);
	
	public List<FolderDTO> searchFolderNameIsSharedFolder(String folderName, String isSharedFolder);
	
	public List<FolderDTO> searchMemberCodeIsSharedFolder(String memberCode,String isSharedFolder);
	
	public List<FolderDTO> searchMemberCodeParentFolderCode(String memberCode, String parentFolderCode);
}
