//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FolderInsertDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import com.soloud.per.dto.FolderDTO;
/**
 * 폴더 데이터를 추가하는 인터페이스
 * @author 장성봉 <hr>
 * 폴더 데이터베이스에 지정한 데이터 가지는 데이터를 <br>
 * 추가하는 인터페이스<br>
 * 이 인터페이스의 메소드가 호출되면 트리거가 발생<br>
 * 트리거의 조건에 따라<br>
 * 공유폴더정보를 가진 데이터베이스에 같은 폴더코드를 가진 데이터를 추가<br>
 */
public interface FolderInsertDAO
{
	/**
	 * 폴더 데이터베이스에 지정한 멤버코드,부모멤버코드,폴더이름,공유폴더여부,폴더url 데이터를<br>
	 * 가지는 Record로 추가하는 메소드<br>
	 * 이 메소드가 호출되면 트리거가 발생<br>
	 * 트리거의 조건에 따라<br>
	 * 공유폴더정보를 가진 데이터베이스에 같은 폴더코드를 가진 데이터를 추가<br>
	 * @param memberCode 멤버코드
	 * @param parentFolderCode 부모멤버코드
	 * @param folderName 폴더이름
	 * @param isSharedFolder 공유폴더여부
	 * @param folderUrl 폴더 url
	 * @return 성공적으로 추가한 경우 -true
	 */
	public boolean insertFolder(String memberCode, String parentFolderCode, String folderName, String isSharedFolder, String folderUrl);
	/**
	 * 폴더 데이터베이스에 지정한 데이터를 <br>
	 * 캡슐화하는 FolderDTO를 추가하는 메소드<br>
	 * 이 메소드가 호출되면 트리거가 발생<br>
	 * 트리거의 조건에 따라<br>
	 * 공유폴더정보를 가진 데이터베이스에 같은 폴더코드를 가진 데이터를 추가<br>
	 * @param dto 멤버코드,부모멤버코드,폴더이름,공유폴더여부,폴더url를 캡슐화한 FolderDTO 객체
	 * @return 성공적으로 추가한 경우 -true
	 */
	public boolean insertFolderDTO(FolderDTO dto);
}
