//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FolderFileVDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;//
import java.util.List;

import com.soloud.per.dto.FolderFileVDTO;
/**
 * 폴더코드 데이터로 파일의 전체정보 조회하는 VIEW 인터페이스
 * @author 장성봉<hr>
 * 폴더 데이터베이스와 파일 데이터베이스에서 지정한 데이터를 가지는 <br>
 * Record를 조회하는 VIEW 인터페이스
 */
public interface FolderFileVDAO
{
	/**
	 * 폴더 데이터베이스와 파일 데이터베이스에서 지정한 폴더코드 데이터를 가지는 <br>
	 * Record를 조회하는 메소드
	 * @param folderCode 폴더코드
	 * @return 폴더코드,폴더내파일코드,파일이름,파일타입,파일최근수정날짜를 캡슐화하고 있는<br>
	 * FolderFileVDTO 객체 List
	 */
	public List<FolderFileVDTO> searchFolderFile(String folderCode);
	/**
	 * 폴더 데이터베이스와 파일 데이터베이스에서 파일의 모든 데이터 Record를 조회하는 메소드
	 * @return 폴더코드,폴더내파일코드,파일이름,파일타입,파일최근수정날짜를 캡슐화하고 있는<br>
	 * FolderFileVDTO 객체 List
	 */
	public List<FolderFileVDTO> searchFolderFile();
}
