

package com.soloud.per.dao;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FolderUpdateDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//




public interface FolderUpdateDAO
{
	public int updateFolderNameFolderCode(String folderCode, String newfolderName);
	public int updateFolderNameMemberCode(String memberCode,String folderName,String newFolderName);
	public int updateFolderParentFolder(String folderCode,String newParentFolderCode);
	public int updateFolderParentFodlerMemberCode(String memberCode,String folderName,String newParentFolderCode);
	public int updateFolderFolderUrl(String folderCode,String newFolderUrl);
	public int updateFolderURLMemberCode(String memberCode,String folderName,String newFolderUrl);
	
	//public int updateFolderNameFolderCode(String folderCode)
}
