package com.soloud.per.dao;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FriendUpdateDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//




public interface FriendUpdateDAO
{
	public int updateFriendGroup(String memberCode, String friendMemberCode, String groupCode);
}
