//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FriendInsertDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import com.soloud.per.dto.FriendDTO;
/**
 * 친구데이터를 추가하는 인터페이스
 * @author 장성봉<hr>
 * 친구 데이터베이스에서 지정한 데이터를 가지는 <br>
 * Record를 추가하는 인터페이스 *
 */
public interface FriendInsertDAO
{
	/**
	 * 친구데이터베이스에서 지정한 그룹코드,멤버코드,친구멤버코드를 가지는 데이터를<br>
	 * Record에 추가하는 메소드
	 * @param groupCode 그룹코드<br>
	 * 그룹코드 : "절친" "친구" "어색한친구"
	 * @param memberCode 멤버코드
	 * @param friendMemberCode 친구멤버코드
	 * @return 성공적으로 추가한 경우 -true
	 */
	public boolean insertFriend(String groupCode, String memberCode, String friendMemberCode);
	/**
	 * 친구데이터베이스에서 지정한 데이터를 캡슐화한 FriendDTO데이터를<br>
	 * Record에 추가하는 메소드
	 * @param dto 친구정보를 캡슐화한 FriendDTO 객체
	 * @return 성공적으로 추가한 경우 -true
	 */
	public boolean insertFriendDTO(FriendDTO dto);
}
