//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FriendDeleteDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 친구데이터를 삭제하는 인터페이스
 * @author 장성봉 <hr>
 * 친구 데이터베이스에서 지정한 데이터를 가지는 <br>
 * Record를 삭제하는 인터페이스<br>
 * 이 인터페이스의 메소드가 호출되면 트리거가 발생<br>
 * 공유폴더의 공유 친구정보를 가진 데이터베이스에서 같은 친구코드를 가진 데이터를 삭제
 */
public interface FriendDeleteDAO
{
	/**
	 * 친구데이터베이스에서 지정한 친구코드를 가지는 <br>
	 * Record를 삭제하는 메소드<br>
	 * 이  메소드가 호출되면 트리거가 발생<br>
	 * 공유폴더의 공유 친구정보를 가진 데이터베이스에서 같은 친구코드를 가진 데이터를 삭제
	 * @param friendCode 친구코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteFriendCode(String friendCode);
	/**
	 * 친구데이터베이스에서 지정한 친구멤버코드를 가지는 <br>
	 * Record를 삭제하는 메소드<br>
	 * 이  메소드가 호출되면 트리거가 발생<br>
	 * 공유폴더의 공유 친구정보를 가진 데이터베이스에서 같은 친구코드를 가진 데이터를 삭제
	 * @param friendMemberCode 친구멤버코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteFriendMemberCode(String friendMemberCode);
	/**
	 * 친구데이터베이스에서 지정한 멤버코드,친구멤버코드를 가지는 <br>
	 * Record를 삭제하는 메소드<br>
	 * 이  메소드가 호출되면 트리거가 발생<br>
	 * 공유폴더의 공유 친구정보를 가진 데이터베이스에서 같은 친구코드를 가진 데이터를 삭제
	 * @param memberCode 멤버코드
	 * @param friendMemberCode 친구멤버코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteMemberCode(String memberCode, String friendMemberCode);
}
