//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FriendSearchDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.List;

import com.soloud.per.dto.FriendDTO;
/**
 * 친구 데이터를 조회하는 인터페이스
 * @author 장성봉<hr>
 * 친구 데이터베이스에서 지정한 데이터를 가지는 <br>
 * Record를 조회하는 인터페이스
 */
public interface FriendSearchDAO 
{
	/**
	 * 친구 데이터베이스의 모든 Record를 조회하는 인터페이스
	 * @return 조회한 Record정보를 캡슐화한 FriendDTO List 객체  
	 */
	public List<FriendDTO> searchAllFriend();
	/**
	 * 친구 데이터베이스에서 지정한 친구코드 데이터를 가지는 <br>
	 * Record를 조회하는 메소드
	 * @param friendCode 친구코드
	 * @return 조회한 Record정보를 캡슐화한 FriendDTO 객체
	 */
	public FriendDTO searchFriendCode(String friendCode);
	/**
	 * 친구 데이터베이스에서 지정한 그룹코드 데이커를 가지는<br>
	 * Record를 조회하는 메소드
	 * @param groupCode 그룹코드
	 * @return 조회한 Record정보를 캡슐화한 FriendDTO List 객체
	 */
	public List<FriendDTO> searchGroupCode(String groupCode);
	/**
	 * 친구 데이터베이스에서 지정한 멤버코드 데이터를 가지는 <br>
	 * Record를 조회하는 메소드
	 * @param memberCode 멤버코드
	 * @return 조회한 Record정보를 캡슐화한 FriendDTO List 객체
	 */
	public List<FriendDTO> searchMemberCode(String memberCode);
	/**
	 * 친구 데이터베이스에서 지정한 그룹코드, 멤버코드를 가지는 <br>
	 * Record를 조회하는 메소드
	 * @param groupCode 그룹코드
	 * @param memberCode 멤버코드
	 * @return 조회한 Record정보를 캡슐화한 FriendDTO List 객체
	 */
	public List<FriendDTO> searchGroupMemberCode(String groupCode, String memberCode);
	/**
	 * 친구 데이터 베이스에서 지정한 멤버코드, 친구멤버코드 데이커를 가지는 <br>
	 * Record를 조회하는 메소드
	 * @param memberCode 멤버코드
	 * @param friendMemberCode 친구멤버코드
	 * @return 조회한 Record정보를 캡슐화한 FriendDTO 객체
	 */
	public FriendDTO searchMemberCodeFriendMemberCode(String memberCode, String friendMemberCode);
}
