//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GroupDeleteDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 그룹 데이터를 삭제하는 인터페이스
 * @author 장성봉<hr>
 * 그룹 데이터베이스에서 지정한 데이터를 가지는<br>
 * Record를 삭제하는 인터페이스<br>
 * 이 인터페이스이 메소드가 호출 되면  트리거가 발생<br>
 * 파일에 접근 가능한 그룹정보를 가진 데이터베이스에서 같은 그룹코드를 가진 모든 데이터 삭제<br>
 * 친구정보를 가진 데이터베이스에서 같은 그룹 코드를 가진 친구정보를 모두 삭제
 */
public interface GroupDeleteDAO
{
	/**
	 * 그룹데이터 베이스에서 지정한 그룹코드 데이터를 가지는<br>
	 * Record를 삭제하는 메소드<br>
	 * 이 인터페이스이 메소드가 호출 되면  트리거가 발생<br>
	 * 파일에 접근 가능한 그룹정보를 가진 데이터베이스에서 같은 그룹코드를 가진 모든 데이터 삭제<br>
	 * 친구정보를 가진 데이터베이스에서 같은 그룹 코드를 가진 친구정보를 모두 삭제
	 * @param groupCode 그룹코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteGroupCode(String groupCode);
	/**
	 * 그룹데이터 베이스에서 지정한 멤버코드 데이터를 가지는<br>
	 * Record를 삭제하는 메소드<br>
	 * 이 인터페이스이 메소드가 호출 되면  트리거가 발생<br>
	 * 파일에 접근 가능한 그룹정보를 가진 데이터베이스에서 같은 그룹코드를 가진 모든 데이터 삭제<br>
	 * 친구정보를 가진 데이터베이스에서 같은 그룹 코드를 가진 친구정보를 모두 삭제
	 * @param memberCode 멤버코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteMemberCode(String memberCode);
	/**
	 * 그룹데이터 베이스에서 지정한 그룹이름 데이터를 가지는<br>
	 * Record를 삭제하는 메소드<br>
	 * 이 인터페이스이 메소드가 호출 되면  트리거가 발생<br>
	 * 파일에 접근 가능한 그룹정보를 가진 데이터베이스에서 같은 그룹코드를 가진 모든 데이터 삭제<br>
	 * 친구정보를 가진 데이터베이스에서 같은 그룹 코드를 가진 친구정보를 모두 삭제
	 * @param groupName 그룹코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteGroupName(String groupName);
}
