//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GroupUpdateDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 그룹 데이터를 변경하는 인터페이스
 * @author 장성봉<hr>
 * 그룹 데이터베이스에서 지정한 데이터를 가지는<br>
 * Record를 지정한 데이터로 변경하는 인터페이스
 */
public interface GroupUpdateDAO
{
	/**
	 * 그룹 데이터베이스에서 지정한 그룹코드 데이커를 가지는 <br>
	 * Record의 그룹 이름을 지정한 그룹이름으로 변경하는 메소드
	 * @param groupCode 그룹코드
	 * @param groupName 그룹이름
	 * @return 성공적으로 변경한 행의 개수
	 */
	public int updateGroupName(String groupCode, String groupName);
}
