//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GroupInsertDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import com.soloud.per.dto.GroupDTO;
/**
 * 그룹 데이터를 추가하는 인터페이스
 * @author 장성봉<hr>
 * 그룹 데이터 베이스에서 지정한 데이터를 가지는<br>
 * Record를 추가하는 인터페이스
 */
public interface GroupInsertDAO
{
	/**
	 * 그룹 데이터베이스에서 지정한 멤버코드,그룹이름 데이터를<br>
	 * Record에 추가하는 메소드
	 * @param memberCode 멤버코드
	 * @param groupName 그룹이름
	 * @return 성공적으로 추가한 경우 -true
	 */
	public boolean insertGroup(String memberCode, String groupName);
	/**
	 * 그룹 데이터베이스에서 지정한 데이터를 캡슐화한 GroupDTO를<br>
	 * Record에 추가하는 메소드
	 * @param dto 데이터를 캡슐화한 GroupDTO 객체
	 * @return 성공적으로 추가한 경우 -true
	 */
	public boolean insertGroupDTO(GroupDTO dto);
}