//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MediaInfoUpdateDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 미디어정보 데이터를 변경하는 인터페이스
 * @author 장성봉<hr>
 * 미디어정보 데이터 베이스에서 지정한 데이터를 가지는<br>
 * Record를 지정한 데이터로 변경하는 인터페이스
 */
public interface MediaInfoUpdateDAO
{
	/**
	 * 미디어정보 데이터베이스에서 지정한 미디어코드를 가지는 <br>
	 * Record의 미디어 시퀀스번호를 지정한 미디어 시퀀스 번호 변경하는 메소드
	 * @param mediaCode 미디어코드
	 * @param mediaSequence 미디어 시퀀스 번호
	 * @return 성공적으로 변경한 행의 개수
	 */
	public int updateMediaSequence(String mediaCode, int mediaSequence);
}
