//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MediaInfoDeleteDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 미디어정보데이터를 삭제하는 인터페이스
 * @author 장성봉<hr>
 * 미디어정보 데이터베이스에서 지정한 데이터를 가지는<br>
 * Record를 삭제하는 인터페이스
 */
public interface MediaInfoDeleteDAO
{
	/**
	 * 미디어정보 데이터 베이스에서 지정한 미디어코드 데이터를 가지는<br>
	 * Record를 삭제하는 메소드
	 * @param mediaCode 미디어 코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteMediaCode(String mediaCode);
	/**
	 * 미디어정보 데이터 베이스에서 지정한 멤버코드 데이터를 가지는<br>
	 * Record를 삭제하는 메소드
	 * @param memberCode 멤버
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteMemberCode(String memberCode);
	/**
	 * 미디어정보 데이터 베이스에서 지정한 파일코드 데이터를 가지는<br>
	 * Record를 삭제하는 메소드
	 * @param fileCode 파일코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteFileCode(String fileCode);
	/**
	 * 미디어정보 데이터 베이스에서 지정한 미디어코드, 멤버코드 데이터를 가지는<br>
	 * Record를 삭제하는 메소드
	 * @param mediaCode
	 * @param memberCode
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteMediaCodeMemberCode(String mediaCode, String memberCode);
	/**
	 * 미디어정보 데이터 베이스에서 지정한 미디어코드,파일코드 데이터를 가지는<br>
	 * Record를 삭제하는 메소드
	 * @param mediaCode 미디어코드
	 * @param fileCode 파일코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteMediaCodeFileCode(String mediaCode, String fileCode);
}
