//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MediaInfoSearchDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.List;

import com.soloud.per.dto.MediaInfoDTO;
/**
 * 미디어정보 데이터를 조회하는 인터페이스
 * @author 장성봉<hr>
 * 미디어정보 데이터베이스에서 지정한 데이터를 <br>
 * 가지는 Record를 조회하는 인터페이스
 */
public interface MediaInfoSearchDAO
{
	/**
	 * 미디어정보 데이터베이스의 모든 Record를 조회하는 메소드
	 * @return 찾은 Record데이터를 캡슐화한 MemdiaInfoDTO 타입의 List객체
	 */
	public List<MediaInfoDTO> searchAllMediaInfo();
	/**
	 * 미디어정보 데이터베이스에서 지정한 미디어코드 데이커를 가지는<br>
	 * Record를 조회하는 메소드
	 * @param mediaCode 미디어 코드
	 * @return 찾은 Record데이터를 캡슐화한 MemdiaInfoDTO 타입의 객체
	 */
	public MediaInfoDTO searchMediaCode(String mediaCode);
	/**
	 * 미디어정보 데이터베이스에서 지정한 멤버코드 데이터를 가지는<br>
	 * Record를 조회하는 메소드
	 * @param memberCode 멤버코드
	 * @return 찾은 Record데이터를 캡슐화한 MemdiaInfoDTO 타입의 List객체
	 */
	public List<MediaInfoDTO> searchMemberCode(String memberCode);
	/**
	 * 미디어정보 데이터베이스에서 지정한 파일코드 데이터를 가지는<br>
	 * Record를 조회하는 메소드
	 * @param fileCode
	 * @return 찾은 Record데이터를 캡슐화한 MemdiaInfoDTO 타입의 List객체
	 */
	public List<MediaInfoDTO> searchFileCode(String fileCode);
	/**
	 * 미디어정보 데이터베이스에서 지정한 멤버코드,파일코드 데이터를 가지는<br>
	 * Record를 조회하는 메소드
	 * @param memberCode
	 * @param fileCode
	 * @return 찾은 Record데이터를 캡슐화한 MemdiaInfoDTO 타입의 객체
	 */
	public MediaInfoDTO searchMemberCodeFileCode(String memberCode, String fileCode);
}
