
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MediaInfoInsertDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import com.soloud.per.dto.MediaInfoDTO;
/**
 * 미디어정보 데이터를 추가하는 인터페이스
 * @author 장성봉
 * 미디어정보 데이터베이스에 지정한 데이터를 가지는<br> 
 * Record를 추가하는 인터페이스
 */
public interface MediaInfoInsertDAO
{
	/**
	 * 미디어정보 데이터베이스에 지정한 멤버코드,파일코드,미디어시퀀스번호 데이터를 <br>
	 * Record에 추가하는 메소드
	 * @param memberCode 멤버코드
	 * @param fileCode 파일코드
	 * @param mediaSequence 미디어 시퀀스 번호
	 * @return 성공적으로 추가한 경우 - true
	 */
	public boolean insert(String memberCode, String fileCode, int mediaSequence);
	/**
	 * 미디어정보 데이터베이스에 지정한 데이터를 캡슐화한 <br>
	 * MediaInfoDTO 객체를 Record에 추가하는 메소드
	 * @param dto  멤버코드,파일코드,미디어시퀀스번호 를 캡슐화한 MediaInfoD	TO객체
	 * @return 성공적으로 추가한 경우 - true
	 */
	public boolean insertMediaInfoDTO(MediaInfoDTO dto);
}