package com.soloud.per.dao;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberUpdateDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//




public interface MemberUpdateDAO
{
	public int updateMemberId(String memberCode, String newMemberId);
	public int updateMemberPwd(String memberCode, String newMemberPwd);
	public int updateMemberLimitCapacity(String memberCode, double newMemberLimitCapacity);
	public int updateMemberName(String memberCode, String newMemberName);
	public int updateMemberName(String memberId, String memberPwd, String newMemberName);
	public int updateMemberPwd(String memberId, String memberPwd, String newMemberPwd);
	public int updateMemberLimitCapacity(String memberId, String memberPwd, double newMemberLimitCapacity);
	public int updateMemberId(String memberId, String memberPwd, String newMemberId);
	public int updateMemberKindCode(String memberId, String memberPwd, String newMemberKindCode);
	public int updateMember(String memberId, String newName, String newPassword);
}
