//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberFileMediaVDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.List;

import com.soloud.per.dto.MemberFileMediaVDTO;
/**
 * 멤버코드로 멤버의 미디어 정보를 조회하는 VIEW 인터페이스
 * @author 장성봉 <hr>
 * 멤버 데이터베이스,파일 데이터베이스, 미디어 데이터 베이스에서
 * 미디어 정보를 조회하는 VIEW 인터페이스
 */
public interface MemberFileMediaVDAO
{
	/**
	 * 멤버 데이터베이스,파일 데이터베이스, 미디어 데이터 베이스에서
	 * 모든 미디어 정보를 조회하는 메소드
	 * @return 사용자코드,미디어코드,파일코드,파일이름,파일유형,미디어시퀀스를 캡슐화 한 MemberFileMediaVDTO List 객체
	 */
	public List<MemberFileMediaVDTO> searchMemberFileMedia();
	/**
	 * 멤버 데이터베이스,파일 데이터베이스, 미디어 데이터 베이스에서
	 * 지정한 멤버코드데이터를 가지는 미디어 정보를 조회하는 메소드
	 * @param memberCode 멤버코드
	 * @return 사용자코드,미디어코드,파일코드,파일이름,파일유형,미디어시퀀스를 캡슐화 한 MemberFileMediaVDTO List 객체
	 */
	public List<MemberFileMediaVDTO> searchMemberFileMedia(String memberCode);
}
