//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberFolderVDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.List;

import com.soloud.per.dto.MemberFolderVDTO;
/**
 * 멤버에 대한 폴더정보를 조회하는 VIEW 인터페이스
 * @author 장성봉<hr>
 * 멤버 데이터베이스, 폴더 데이터 베이스에서 멤버에 대한<br>
 * 폴더정보를 조회하는 VIEW 인터페이스
 */
public interface MemberFolderVDAO
{
	/**
	 * 멤버 데이터베이스, 폴더 데이터 베이스의 모든 멤버에 대한 폴더정보를 <br>
	 * 조회하는 메소드
	 * @return 멤버코드,멤버의폴더코드,폴더의이름,폴더의부모폴더코드를 캡슐화한 MemberFolderVDTO List 객체
	 */
	public List<MemberFolderVDTO> searchMemberFolder();
	/**
	 * 멤버 데이터베이스, 폴더 데이터 베이스의 지정한 멤버코드의  멤버에 대한 폴더정보를 <br>
	 * 조회하는 메소드
	 * @param memberCode 멤버코드
	 * @return 멤버코드,멤버의폴더코드,폴더의이름,폴더의부모폴더코드를 캡슐화한 MemberFolderVDTO List 객체
	 */
	public List<MemberFolderVDTO> searchMemberFolder(String memberCode);
}
