//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberAlarmVDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.List;

import com.soloud.per.dto.MemberAlarmVDTO;
/**
 * 멤버코드로 알람정보를 조회하는 VIEW 인터페이스
 * @author 장성봉<hr>
 * 멤버 데이터베이스와 알람 데이터 베이스, 알람유형 데이터베이스에서 지정한 데이터<br>
 * 를 가지는 알람정보를 조회하는 VIEW 인터페이스 *
 */
public interface MemberAlarmVDAO
{
	/**
	 * 멤버 데이터베이스와 알람데이터베이스, 알람유형 데이터 베이스에서 지정한 멤버코드 데이터를 가지는 <br>
	 * 알람정보를 조회하는 메소드
	 * @param memberCode 멤버코드
	 * @return 멤버코드, 받는사람이름 , 보낸사람코드,보낸사람이름,알림날짜,알림유형, 수신확인여부를 캡슐화한 MemberAlarmVDTO List 객체
	 */
	public List<MemberAlarmVDTO> searchMemberAlarm(String memberCode);
	/**
	 * 멤버 데이터베이스와 알람데이터베이스,알람유형 데이터 베이스의 알람정보를 조회하는 메소드
	 * @return 멤버코드, 받는사람이름 , 보낸사람코드,보낸사람이름,알림날짜,알림유형, 수신확인여부를 캡슐화한 MemberAlarmVDTO List 객체
	 */
	public List<MemberAlarmVDTO> searchMemberAlarm();
}
