//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberFileVDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.List;

import com.soloud.per.dto.MemberFileVDTO;
/**
 * 멤버에 대한 파일정보를  조회하는 VIEW 인터페이스
 * @author 장성봉 <hr>
 * 멤버 데이터베이스, 파일 데이터베이스에서 멤버에 대한
 * 파일정보를 조회하는 VIEW 인터페이스
 */
public interface MemberFileVDAO
{
	/**
	 * 멤버 데이터베이스, 파일 데이터베이스의 지정한 멤버코드를 가지는 데이터를<br>
	 * 조회하는 메소드
	 * @param memberCode 멤버코드
	 * @return 멤버코드,파일코드,최근수정날짜,파일코멘트,파일타입,파일용량,파일이름을 캡슐화한 MemberFileVDTO List 객체
	 */
	public List<MemberFileVDTO> searchMemberFile(String memberCode);
	/**
	 * 멤버 데이터베이스, 파일 데이터베이스의 모든 멤버에 대한 파일정보를 <br>
	 * 조회하는 메소드
	 * @return 멤버코드,파일코드,최근수정날짜,파일코멘트,파일타입,파일용량,파일이름을 캡슐화한 MemberFileVDTO List 객체
	 */
	public List<MemberFileVDTO> searchMemberFile();
}
