//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberKindUpdateDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 멤버유형 데이터를 변경하는 인터페이스
 * @author 장성봉<hr>
 * 멤버유형 데이터베이스에서 지정한 데이터를 가지는 Record를 지정한 데이터로 변경하는 인터페이스
 *
 */
public interface MemberKindUpdateDAO extends DAO
{
	/**
	 * 멤버유형 데이터베이스에서 지정한 멤버유형코드 데이터를 가지는 Record를 지정한 멤버유형 이름 데이터로 변경하는 인터페이스
	 * @param memberKindCode
	 * @param memberKindName
	 * @return 성공적으로 변경한 행의 개수
	 */
	public int updateMemberKindName(String memberKindCode, String memberKindName);
}
