//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberKindDeleteDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 멤버유형 데이터를 삭제하는 인터페이스
 * @author 장성봉<hr>
 * 멤버유형 데이터베이스에서 지정한 데이터를 가지는 Record를 삭제하는 인터페이스<br>
 * 이 인터페이스의 메소드가 호출되면 트리거가 발생<br>
 * 멤버정보를 가진 데이터베이스에서 같은 멤버유형코드를 가진 모든 데이터를 삭제
 */
public interface MemberKindDeleteDAO extends DAO
{
	/**
	 * 멤버유형 데이터베이스에서 지정한 멤버유형코드 데이터를 가지는 Record를 삭제하는 인터페이스
	 * @param memberKindCode 멤버유형 코드<br>
	 * 이 메소드가 호출되면 트리거가 발생<br>
	 * 멤버정보를 가진 데이터베이스에서 같은 멤버유형코드를 가진 모든 데이터를 삭제
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteMemberKind(String memberKindCode);
}
