//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberKindInsertDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import com.soloud.per.dto.MemberKindDTO;
/**
 * 멤버유형 데이터를 추가하는 인터페이스
 * @author 장성봉<hr>
 * 멤버유형 데이터베이스에 지정한 데이터를 Record로 추가하는 인터페이스
 */
public interface MemberKindInsertDAO extends DAO
{
	/**
	 * 멤버유형 데이터베이스에 지정한 멤버유형 이름 데이터를 Record로 추가하는 인터페이스
	 * @param memberKindName 멤버유형 이름
	 * 멤버유형이름 : "관리자" "사용자"
	 * @return 성공적으로 추가한 경우 -true
	 */
	public boolean insertMemberKind(String memberKindName);
	/**
	 * 멤버유형 데이터베이스에 지정한 멤버유형코드,멤버유형이름 데이터를 Record로 추가하는 인터페이스
	 * @param dto 멤버유형코드와 멤버이름을 캡슐화한 MemberKindDTO 객체
	 * 멤버유형이름 : "관리자" "사용자"
	 * @return 성공적으로 추가한 경우 -true
	 */
	public boolean insertMemberKindDTO(MemberKindDTO dto);
}
