//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberInsertDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import com.soloud.per.dto.MemberDTO;
/**
 * 멤버 데이터를 추가하는 인터페이스
 * @author 장성봉<hr>
 * 멤버 데이터베이스에서 지정한 데이터를 <br>
 * Record로 추가 하는 인터페이스<br>
 * 이 인터페이스의 메소드가 호출되면 트리거가 발생<br>
 * 그룹정보를 가진 데이터베이스에 같은 멤버코드를 가진 '절친'그룹이름을 가진 데이터를 추가<br>
 * 그룹정보를 가진 데이터베이스에 같은 멤버코드를 가진 '친구'그룹이름을 가진 데이터를 추가<br>
 * 그룹정보를 가진 데이터베이스에 같은 멤버코드를 가진 '어색한친구'그룹이름을 가진 데이터를 추가<br>
 */
public interface MemberInsertDAO
{
	/**
	 * 멤버 데이터베이스에 지정한 멤버아이디,용량,멤버비밀번호,멤버이름을 <br>
	 * Record로 추가하는 메소드<br>
	 * 이  메소드가 호출되면 트리거가 발생<br>
	 * 그룹정보를 가진 데이터베이스에 같은 멤버코드를 가진 '절친'그룹이름을 가진 데이터를 추가<br>
	 * 그룹정보를 가진 데이터베이스에 같은 멤버코드를 가진 '친구'그룹이름을 가진 데이터를 추가<br>
	 * 그룹정보를 가진 데이터베이스에 같은 멤버코드를 가진 '어색한친구'그룹이름을 가진 데이터를 추가<br>
	 * @param memberId 멤버아이디
	 * @param memberLimitCapacity 멤버의용량
	 * @param memberPwd 멤버의비밀번호
	 * @param memberName 멤버의 이름
	 * @return 성공적으로 추가한 경우 - true
	 */
	public boolean insertMember(String memberId, double memberLimitCapacity, String memberPwd, String memberName);
	/**
	 * 멤버 데이터베이스에 지정한 멤버아이디,용량,멤버비밀번호,멤버이름을 <br>
	 * Record로 추가하는 메소드<br>
	 * 이  메소드가 호출되면 트리거가 발생<br>
	 * 그룹정보를 가진 데이터베이스에 같은 멤버코드를 가진 '절친'그룹이름을 가진 데이터를 추가<br>
	 * 그룹정보를 가진 데이터베이스에 같은 멤버코드를 가진 '친구'그룹이름을 가진 데이터를 추가<br>
	 * 그룹정보를 가진 데이터베이스에 같은 멤버코드를 가진 '어색한친구'그룹이름을 가진 데이터를 추가<br>
	 * @param dto 멤버아이디,용량,멤버비밀번호,멤버이름을 <br>
	 * 캡슐화한 MemberDTO 객체
	 * @return 성공적으로 추가한 경우 - true
	 */
	public boolean insertMebmberDTO(MemberDTO dto);
}
