//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberSharedVDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.List;

import com.soloud.per.dto.MemberSharedVDTO;
/**
 * 멤버의 공유폴더정보를 조회하는 VIEW 인터페이스
 * @author 장성봉<hr>
 * 멤버 데이터베이스와 공유폴더 데이터베이스, 폴더 데이터베이스에서 멤버에 대한 공유폴더정보를 조회하는 VIEW 인터페이스
 */
public interface MemberSharedVDAO
{
	/**
	 * 멤버 데이터베이스와 공유폴더 데이터베이스, 폴더 데이터베이스에서 지정한 멤버코드 데이터를 가지는  공유폴더정보를 조회하는 메소드
	 * @param memberCode 멤버코드
	 * @return 멤버코드,공유폴더코드,폴더코드,폴더이름,폴더의 실제위치URL,공유폴더만든날 데이터를 캡슐화한 MemberSharedVDTO List 객
	 */
	public List<MemberSharedVDTO> searchMemberShared(String memberCode);
	/**
	 * 멤버 데이터베이스와 공유폴더 데이터베이스, 폴더 데이터베이스에서 모든 멤버에 대한 공유폴더정보를 조회하는 메소드
	 * @return 멤버코드,공유폴더코드,폴더코드,폴더이름,폴더의 실제위치URL,공유폴더만든날 데이터를 캡슐화한 MemberSharedVDTO List 객체
	 */
	public List<MemberSharedVDTO> searchMemberShared();
	
	//
	public MemberSharedVDTO searchMemberSharedFolder(String memberCode, String folderCode);
}
