//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReplyDeleteDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.GregorianCalendar;
/**
 * 댓글 데이터를 삭제하는 인터페이스
 * @author 장성봉<hr>
 * 댓글 인터페이스에서 지정한 데이터를 가지는 Record를 삭제하는 인터페이스
 */
public interface ReplyDeleteDAO
{
	/**
	 * 댓글 인터페이스에서 지정한 댓글코드 데이터를 가지는 Record를 삭제하는 메소드
	 * @param replyCode 댓글코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteReplyCode(String replyCode);
	/**
	 * 댓글 인터페이스에서 지정한 공유폴더 코드 데이터를 가지는 Record를 삭제하는 메소드
	 * @param sharedFolderCode 공유폴더 코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteSharedFolderCode(String sharedFolderCode);
	/**
	 * 댓글 인터페이스에서 지정한 데이터를 가지는 Record를 삭제하는 메소드
	 * @param memberCode 멤버코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteMemberCode(String memberCode);
	/**
	 * 댓글 인터페이스에서 지정한 멤버코드, 기간 ,공유폴더 코드 데이터를 가지는 Record를 삭제하는 메소드
	 * @param memberCode 멤버코드
	 * @param startDate 삭제 할 댓글의 시작 날짜
	 * @param endDate 삭제 할 댓글의 마지막 날짜
	 * @param sharedFolderCode 공유폴더 코드
	 * @return 성공적으로 삭제한 행의 개수
	 */
	public int deleteMemberCodeReplyWritedateSharedFolderCode(String memberCode, GregorianCalendar startDate, GregorianCalendar endDate, String sharedFolderCode);
}
