//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReplyUpdateDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
/**
 * 댓글 데이터를 변경하는 인터페이스
 * @author 장성봉<hr>
 * 댓글 인터페이스에서 지정한 데이터를 가지는 Record를 지정한 데이터로 변경하는 인터페이스
 */
public interface ReplyUpdateDAO
{
	/**
	 * 댓글 인터페이스에서 지정한 댓글코드 데이터를 가지는 Record의 댓글내용을  지정한 댓글내용 데이터로 변경하는 인터페이스
	 * @param replyCode 댓글코드
	 * @param newReplyContent 변경 할 댓글내용
	 * @return 성공적으로 변경한 행의 개수
	 */
	public int updateReplyContent(String replyCode, String newReplyContent);
	/**
	 * 댓글 인터페이스에서 지정한 멤버코드,공유폴더코드데이터를 가지는 Record의 댓글 내용을 지정한 댓글내용 데이터로 변경하는 인터페이스
	 * @param memberCode 멤버코드
	 * @param shared_folder_code 공유폴더코드
	 * @param newReplyContent 댓글 내용
	 * @return 성공적으로 변경한 행의 개수
	 */
	public int updateReplyContent(String memberCode, String shared_folder_code, String newReplyContent);
}
