package com.soloud.per.dao;//
import java.util.GregorianCalendar;

import com.soloud.per.dto.ReplyDTO;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReplyInsertDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//

/**
 * 댓글 데이터를 추가하는 인터페이스
 * @author 장성봉<hr>
 * 댓글 데이터베이스에 지정한 데이터를 Record로 추가하는 인터페이스 
 */
public interface ReplyInsertDAO
{
	/**
	 * 댓글 데이터베이스에 지정한 공퓨폴더 코드,멤버코드,댓글 작설일, 댓글내용 데이터를 Record로 추가하는 메소드
	 * @param sharedFolderCode 공유폴더 코드
	 * @param memberCode 멤버코드
	 * @param replyWritedate 댓글 작성일
	 * @param replyContent 댓글 내용
	 * @return 성공적으로 추가한 경우 - true
	 */
	public boolean insertReply(String sharedFolderCode, String memberCode, GregorianCalendar replyWritedate, String replyContent);
	/**
	 * 댓글 데이터베이스에 지정한 데이터를 공퓨폴더 코드,멤버코드,댓글 작설일, 댓글내용 데이터 Record로 추가하는 메소드
	 * @param dto 공퓨폴더 코드,멤버코드,댓글 작설일, 댓글내용 데이터를 캡슐화한 ReplyDTO 객체
	 * @return 성공적으로 추가한 경우  - true
	 */
	public boolean insertReplyDTO(ReplyDTO dto);
}
