//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReplySearchDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.GregorianCalendar;
import java.util.List;

import com.soloud.per.dto.ReplyDTO;
/**
 * 댓글 데이터를 조회하는 인터페이스
 * @author 장성봉 <hr>
 * 댓글 데이터베이스에서 지정한 데이터를 가지는 Record를 조회하는 인터페이스
 */
public interface ReplySearchDAO
{
	/**
	 * 댓글 데이터베이스에서 모든 Record를 조회하는 메소드
	 * @return 댓글정보를 캡슐화 하고 있는 ReplyDTO List 객체
	 */
	public List<ReplyDTO> searchAllReply();
	/**
	 * 댓글 데이터베이스에서 지정한 댓글 코드데이터를 가지는 Record를 조회하는 메소드
	 * @param replyCode 댓글 코드
	 * @return 댓글정보를 캡슐화 하고 있는 ReplyDTO 객체
	 */
	public ReplyDTO searchReplyCode(String replyCode);
	/**
	 * 댓글 데이터베이스에서 지정한 공유폴더 코드 데이터를 가지는 Record를 조회하는 메소드
	 * @param sharedFolderCode 공유폴더 코드
	 * @return 댓글정보를 캡슐화 하고 있는 ReplyDTO List 객체
	 */
	public List<ReplyDTO> searchSharedFolderCode(String sharedFolderCode);
	/**
	 * 댓글 데이터베이스에서 지정한 멤버코드 데이터를 가지는 Record를 조회하는 메소드
	 * @param memberCode 멤버코드
	 * @return 댓글정보를 캡슐화 하고 있는 ReplyDTO List 객체
	 */
	public List<ReplyDTO> searchMemberCode(String memberCode);
	/**
	 * 댓글 데이터베이스에서 지정한 기간내의 작성일 데이터를 가지는 Record를 조회하는 메소드
	 * @param startDate 찾을 댓글데이터의 작성 시작일
	 * @param endDate 찾을 댓글데이터의 작성 마지막일
	 * @return 댓글정보를 캡슐화 하고 있는 ReplyDTO List 객체
	 */
	public List<ReplyDTO> searchReplyWriteDate(GregorianCalendar startDate, GregorianCalendar endDate);
	/**
	 * 댓글 데이터베이스에서 지정한 공유폴더코드,멤버코드 데이터를 가지는 Record를 조회하는 메소드
	 * @param sharedFolderCode 공유폴더 코드
	 * @param memberCode 멤버코드
	 * @return 댓글정보를 캡슐화 하고 있는 ReplyDTO List 객체
	 */
	public List<ReplyDTO> searchReplyShardFolderCodeMemberCode(String sharedFolderCode, String memberCode);
}
