//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SharedFolderSearchDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.List;

import com.soloud.per.dto.SharedFolderDTO;
/**
 * 공유폴더데이터를 조회하는 인터페이스
 * @author 장성봉<hr>
 * 공유폴더 데이터베이스에서 지정한 데이터를 가지는 Record를 조회하는 인터페이스
 */
public interface SharedFolderSearchDAO
{
	/**
	 * 공유폴더 데이터베이스에서 모든 Record를 조회하는 메소드
	 * @return 공유폴더코드,폴더코드,공유폴더생성일 데이터를 캡슐화한 SharedFolderDTO List 객체
	 */
	public List<SharedFolderDTO> searchAllSharedFolder();
	/**
	 * 공유폴더 데이터베이스에서 지정한 공유폴더코드 데이터를 가지는 Record를 조회하는 메소드
	 * @param sharedFolderCode 공유폴더 코드
	 * @return 공유폴더코드,폴더코드,공유폴더생성일 데이터를 캡슐화한 SharedFolderDTO List 객체
	 */
	public SharedFolderDTO searchSharedFolderCode(String sharedFolderCode);
	/**
	 * 공유폴더 데이터베이스에서 지정한 폴더코드 데이터를 가지는 Record를 조회하는 메소드
	 * @param folderCode 폴더코드
	 * @return 공유폴더코드,폴더코드,공유폴더생성일 데이터를 캡슐화한 SharedFolderDTO List 객체
	 */
	public SharedFolderDTO searchFolderCode(String folderCode);
}
