//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SharedFileVDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;//
import java.util.List;

import com.soloud.per.dto.SharedFileVDTO;
/**
 * 공유파일에 대한 파일 정보를 조회하는 VIEW 인터페이스
 * @author 장성봉<hr>
 * 공유폴더 데이터 베이스와 폴더 데이터 베이스, 파일 데이터 베이스에서 지정한 데이터를 가지는 Record를 조회하는 VIEW 인터페이스
 */
public interface SharedFileVDAO
{
	/**
	 * 공유폴더 데이터 베이스와 폴더 데이터 베이스, 파일 데이터 베이스에서 지정한 공유폴더코그 데이터를 가지는 공유파일의 파일정보를 조회하는 메소드
	 * @param sharedFolderCode 공유폴더 코드
	 * @return 공유폴더코드,공유폴더실제폴더코드,공유폴더내파일코드,파일이름,파일최근수정날짜,파일타입 데이터를 캡슐화 하고 있는 SharedFileVDTO List 객체
	 */
	public List<SharedFileVDTO> searchSharedFile(String sharedFolderCode);
	/**
	 * 공유폴더 데이터 베이스와 폴더 데이터 베이스, 파일 데이터 베이스에서 모든 공유파일의 파일정보를 조회하는 메소드
	 * @return 공유폴더코드,공유폴더실제폴더코드,공유폴더내파일코드,파일이름,파일최근수정날짜,파일타입 데이터를 캡슐화 하고 있는 SharedFileVDTO List 객체
	 */
	public List<SharedFileVDTO> searchSharedFile();
}
