//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SharedFriendVDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.List;

import com.soloud.per.dto.SharedFriendVDTO;
/**
 * 공유폴더에 대한 공유친구 정보를 조회하는 VIEW 인터페이스
 * @author 장성봉<hr>
 * 공유폴더데이터베이스, 친구데이터베이스에서 지정한 데이터를 가지는 공유폴더 의 친구정보를 조회하는 VIEW 인터페이스 
 */
public interface SharedFriendVDAO
{
	/**
	 * 공유폴더데이터베이스, 친구데이터베이스에서 지정한 공유폴더코드 데이터를 가지는 공유폴더 의 친구정보를 조회하는 메소드 
	 * @param sharedFolderCode 공유폴더코드
	 * @return 공유폴더코드,친구코드,친구아이디,친구이름 데이터를 캡슐화한 SharedFriendVDTO List 객체
	 */
	public List<SharedFriendVDTO> searchSharedFriend(String sharedFolderCode);
	/**
	 * 공유폴더데이터베이스, 친구데이터베이스에서 지정한 공유폴더코드 데이터를 가지는 공유폴더 의 친구정보를 조회하는 메소드 
	 * @param sharedFolderCode 공유폴더코드, memberCode 멤버코드
	 * @return 공유폴더코드,친구코드,친구아이디,친구이름 데이터를 캡슐화한 SharedFriendVDTO List 객체
	 */
	public List<SharedFriendVDTO> searchSharedFriend(String sharedFolderCode, String memberCode);
	public SharedFriendVDTO searchSharedFriend(String sharedFolderCode, String memberCode, String friendMemberCode);
	/**
	 * 공유폴더데이터베이스, 친구데이터베이스에서 모든 공유폴더 의 친구정보를 조회하는 메소드 
	 * @return 공유폴더코드,친구코드,친구아이디,친구이름 데이터를 캡슐화한 SharedFriendVDTO List 객체
	 */
	public List<SharedFriendVDTO> searchSharedFriend();
}
