//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SharedFolderInsertDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;//
import java.util.GregorianCalendar;

import com.soloud.per.dto.SharedFolderDTO;
/**
 * 공유폴더 데이터를 추가하는 인터페이스
 * @author 장성봉<hr>
 * 공유폴더 데이터베이스에 지정한 데이터를 Record로 추가하는 인터페이스 
 */
public interface SharedFolderInsertDAO
{
	/**
	 * 공유폴더 데이터베이스에 지정한 폴더코드 ,폴더생성일 데이터 가지는 데이터를 Record로 추가하는 메소드
	 * @param folderCode 폴더코드
	 * @param makeDate 폴더생성일
	 * @return 성공적으로 추가한 경우 - true
	 */
	public boolean insertSharedFolder(String folderCode, GregorianCalendar makeDate);
	/**
	 * 공유폴더 데이터베이스에 지정한 폴더코드 ,폴더생성일 데이터 가지는 데이터를 Record로 추가하는 메소드
	 * @param dto 공유폴더코드,폴더코드,폴더생성일 데이터를 캡슐화한 SharedFodlerDTO 객체
	 * @return 성공적으로 추가한 경우 - true
	 */
	public boolean insertSharedFolderDTO(SharedFolderDTO dto);
}
