//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SharedFolderReplyVDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.List;

import com.soloud.per.dto.SharedFolderReplyVDTO;
/**
 * 공유폴더에 대한 댓글정보를 조회하는 VIEW 인터페이스
 * @author 장성봉 <hr>
 * 공유폴더 데이터베이스,댓글 데이터베이스에서 지정한 데이터를 가지는 Record를 조회하는 VIEW 인터페이스
 */
public interface SharedFolderReplyVDAO
{
	/**
	 * 공유폴더 데이터베이스,댓글데이터베이스,폴더데이터베이스에서  모든 공유폴더의 댓글정보를 조회하는 메소드
	 * @return 공유폴더코드,댓글코드,사용자코드,사용자이름,작성일,내용을 캡슐화한 SharedFolderReplyVDTO List객체
	 */
	public List<SharedFolderReplyVDTO> searchSharedFolderReply();
	/**
	 * 공유폴더 데이터베이스,댓글데이터베이스,폴더데이터베이스에서  지정한 공유폴더코드 데이터를 가지는 공유폴더의 댓글정보를 조회하는 메소드
	 * @param sharedFolderCode 공유폴더 코드
	 * @return 공유폴더코드,댓글코드,사용자코드,사용자이름,작성일,내용을 캡슐화한 SharedFolderReplyVDTO List객체
	 */
	public List<SharedFolderReplyVDTO> searchSharedFolderReply(String sharedFolderCode);
}
