//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SharedFolderUpdateDAO.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//
package com.soloud.per.dao;
import java.util.GregorianCalendar;
/**
 * 공유폴더데이터를 변경하는 인터페이스
 * @author 장성봉<hr>
 * 공유폴더 데이터베이스에서 지정한 데이터를 가지는 Record를 지정한 데이터로 변경하는 인터페이스
 */
public interface SharedFolderUpdateDAO
{
	/**
	 * 공유폴더 데이터베이스에서 지정한 공유폴더코드 데이터를 가지는 Record의 생성일 데이터를 지정한 생성날짜 데이터로 변경하는 인터페이스
	 * @param sharedFolderCode 공유폴더코드
	 * @param makeDate 변경할 생성일
	 * @return 성공적으로 변경한 행의 개수
	 */
	public int updateSharedFolderMakeDate(String sharedFolderCode, GregorianCalendar makeDate);
}
