package com.soloud.pre.validator;
import java.util.ArrayList;

import com.soloud.app.man.FolderManager;
import com.soloud.pre.uiform.FolderManageForm;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FolderManageValidator.java
//  @ Date : 2014-07-21
//  @ Author : 
//
//




public class FolderManageValidator {
	private ArrayList<String> errors;
	
	public FolderManageValidator() {
		this.errors = new ArrayList<String>();
	}

	public FolderManageValidator(ArrayList<String> errors) {
		this.errors = errors;
	}
	/**
	 * 폴더 추가 시 유효성 체크
	 * @param folderManageForm
	 */
	public void validateAdd(FolderManageForm folderManageForm) 
	{
		if(folderManageForm.getFolderName()==null)
		{
			errors.add("폴더 이름을 입력해주세요");
		}
	}
	/**
	 * 폴더 명 변경 시 유효성 체크
	 * @param folderManageForm
	 */
	public void validateName(FolderManageForm folderManageForm) 
	{
		if(folderManageForm.getFolderName()==null)
		{
			errors.add("폴더 이름을 입력해주세요");
		}
	}
	/**
	 * 폴더 경로 수정 시 유효성 체크
	 * @param folderManageForm
	 */
	public void validatePath(FolderManageForm folderManageForm) {
	
	}
	/**
	 * 폴더 삭제 시 유효성 체크
	 * @param folderManageForm
	 */
	public void validateDelete(FolderManageForm folderManageForm) 
	{
		if(folderManageForm.getFolderName()==null)
		{
			errors.add("폴더 이름을 입력해주세요");
		}
	}
	/**
	 * 폴더 복붙 시 유효성 체크
	 * @param folderManageForm
	 */
	public void validateCopy(FolderManageForm folderManageForm) 
	{
		if(folderManageForm.getFolderName()==null)
		{
			errors.add("폴더 이름을 입력해주세요");
		}
	}

	public ArrayList<String> getErrors() {
		return errors;
	}

	public void setErrors(ArrayList<String> errors) {
		this.errors = errors;
	}

	@Override
	public String toString() {
		return "FolderManageValidator [errors=" + errors + "]";
	}
	
}
