//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberManageValidator.java
//  @ Date : 2014-07-21
//  @ Author : 
//
//


package com.soloud.pre.validator;

import java.util.ArrayList;

import com.soloud.pre.uiform.MemberManageForm;

public class MemberManageValidator {
	private ArrayList<String> errors;
	
	public MemberManageValidator() {
		this.errors = new ArrayList<String>();
	}

	public MemberManageValidator(ArrayList<String> errors) {
		this.errors = errors;
	}
	/**
	 * 정보수정 시 유효성 체크
	 * @param memberManageForm
	 */
	public void validateModify(MemberManageForm memberManageForm)
	{
		if(memberManageForm.getNewName()==null || memberManageForm.getNewPassword()==null || memberManageForm.getNewRepassword()==null)
		{
			errors.add("모든 항목을 입력해주세요");
			return;
		}
		
		
			
		String name=memberManageForm.getNewName().trim();
		String pass=memberManageForm.getNewPassword().trim();
		String newPass=memberManageForm.getNewRepassword().trim();
		
		if(name.length()<2)
		{
			errors.add("이름이 짧아요 2자 이상 써주세요");
		}
		if(pass.length()<4)
		{
			errors.add("비밀번호가 짧아요 4자이상 써주세요");
		}
		if(newPass.length()<4)
		{
			errors.add("비밀번호가 짧아요 4자이상 써주세요");
		}
		if(!pass.equals(newPass))
		{
			errors.add("비밀번호가 일치하지 않네요 ㅠ");
		}
	}

	public ArrayList<String> getErrors() {
		return errors;
	}

	public void setErrors(ArrayList<String> errors) {
		this.errors = errors;
	}

	@Override
	public String toString() {
		return "MemberManageValidator []";
	}
	
}
