//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SharedFolderManageValidator.java
//  @ Date : 2014-07-21
//  @ Author : 
//
//


package com.soloud.pre.validator;

import java.util.ArrayList;

import com.soloud.pre.uiform.SharedFolderManageForm;

public class SharedFolderManageValidator {
	private ArrayList<String> errors;
	
	public SharedFolderManageValidator() {
		this.errors = new ArrayList<String>();
	}

	public SharedFolderManageValidator(ArrayList<String> errors) {
		this.errors = errors;
	}
	/**
	 * 공유폴더 추가시 유효성 체크
	 * @param sharedFolderManageForm
	 */
	public void validateAdd(SharedFolderManageForm sharedFolderManageForm) {
	
	}
	/**
	 * 공유폴더 삭제시 유효성 체크
	 * @param sharedFolderManageForm
	 */
	public void validateDelete(SharedFolderManageForm sharedFolderManageForm) {
	
	}
	/**
	 * 공유폴더 초대시 유효성 체크
	 * @param sharedFolderManageForm
	 */
	public void validateInvite(SharedFolderManageForm sharedFolderManageForm) {
	
	}

	public ArrayList<String> getErrors() {
		return errors;
	}

	public void setErrors(ArrayList<String> errors) {
		this.errors = errors;
	}

	@Override
	public String toString() {
		return "SharedFolderManageValidator [getClass()=" + getClass()
				+ ", hashCode()=" + hashCode() + ", toString()="
				+ super.toString() + "]";
	}
	
}
