//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FriendManageForm.java
//  @ Date : 2014-07-21
//  @ Author : 
//
//


package com.soloud.pre.uiform;
/**
 * 친구관리에서 필요한 모든 UI데이터를 캡슐화한 클래스
 * @author 영진
 *
 */
public class FriendManageForm {
	private String friendId;
	private String newGroup;
	public FriendManageForm() {
	}
	public FriendManageForm(String friendId, String newGroup) {
		this.friendId = friendId;
		this.newGroup = newGroup;
	}
	public String getFriendId() {
		return friendId;
	}
	public void setFriendId(String friendId) {
		this.friendId = friendId;
	}
	public String getNewGroup() {
		return newGroup;
	}
	public void setNewGroup(String newGroup) {
		this.newGroup = newGroup;
	}
	@Override
	public String toString() {
		return "FriendManageForm [friendId=" + friendId + ", newGroup="
				+ newGroup + "]";
	}
	
	
}
