//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FriendSearchForm.java
//  @ Date : 2014-07-21
//  @ Author : 
//
//


package com.soloud.pre.uiform;
/**
 * 친구검색에서 필요한 모든 UI데이터를 캡슐화한 클래스
 * @author 영진
 *
 */
public class FriendSearchForm {
	private String friendName;
	private String friendId;
	private String searchScope;
	
	public FriendSearchForm() {
	}

	public FriendSearchForm(String friendName, String friendId,
			String searchScope) {
		this.friendName = friendName;
		this.friendId = friendId;
		this.searchScope = searchScope;
	}

	public String getFriendName() {
		return friendName;
	}

	public void setFriendName(String friendName) {
		this.friendName = friendName;
	}

	public String getFriendId() {
		return friendId;
	}

	public void setFriendId(String friendId) {
		this.friendId = friendId;
	}

	public String getSearchScope() {
		return searchScope;
	}

	public void setSearchScope(String searchScope) {
		this.searchScope = searchScope;
	}

	@Override
	public String toString() {
		return "FriendSearchForm [friendName=" + friendName + ", friendId="
				+ friendId + ", searchScope=" + searchScope + "]";
	}
	
	
}
