//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberManageForm.java
//  @ Date : 2014-07-21
//  @ Author : 
//
//


package com.soloud.pre.uiform;
/**
 * 회원관리에서 필요한 모든 UI데이터를 캡슐화한 클래스
 * @author 영진
 *
 */
public class MemberManageForm {
	private String newName;
	private String newPassword;
	private String newRepassword;
	public MemberManageForm() {
	}
	public MemberManageForm(String newName, String newPassword,
			String newRepassword) {
		this.newName = newName;
		this.newPassword = newPassword;
		this.newRepassword = newRepassword;
	}
	public String getNewName() {
		return newName;
	}
	public void setNewName(String newName) {
		this.newName = newName;
	}
	public String getNewPassword() {
		return newPassword;
	}
	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}
	public String getNewRepassword() {
		return newRepassword;
	}
	public void setNewRepassword(String newRepassword) {
		this.newRepassword = newRepassword;
	}
	@Override
	public String toString() {
		return "MemberManageForm [newName=" + newName + ", newPassword="
				+ newPassword + ", newRepassword=" + newRepassword + "]";
	}
	
	
}
