package com.soloud.per.factory;
import com.soloud.per.dao.DAO;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DAOFactory.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//




public class DAOFactory implements Factory
{
	private static DAOFactory daoFactory;
	public static synchronized Factory getInstance()
	{
		if(daoFactory==null)
			daoFactory = new DAOFactory();
		return daoFactory;
	}
	
	public DAO create(String daoName)
	{
	
		switch(daoName)
		{
			case "Alarm":
			{
				return createAlarmDAO();
			}
			case "AlarmKind":
			{
				return createAlarmKindDAO();
			}
			case "AvailableFileAuthGroup":
			{
				return createAvailableFileAuthGroupDAO();
			}
			case "AvailableFoldeFriend":
			{
				return createAvailableFolderFriendDAO();
			}
			case "FileBinary":
			{
				return createFileBinaryDAO();
			}
			case "File":
			{
				return createFileDAO();
			}
			case "Folder":
			{
				return createFolderDAO();
			}
			case "Friend":
			{
				return createFriendDAO();
			}
			case "Group":
			{
				return createGroupDAO();
			}
			case "MediaInfo":
			{
				return createMediaInfoDAO();
			}
			case "Member":
			{
				return createMemberDAO();
			}
			case "MemberKind":
			{
				return createMemberKindDAO();
			}
			case "Reply":
			{
				return createReplyDAO();
			}
			case "SharedFolder":
			{
				return createSharedFolderDAO();
			}
			case "FileGroupView":
			{
				return createFileGroupVDAO();
			}
			case "FolderFileView":
			{
				return createFolderFileVDAO();
			}
			case "MemberAlarmView":
			{
				return createMemberAlarmVDAO();
			}
			case "MemberFileMediaView":
			{
				return createMemberFileMediaVDAO();
			}
			case "MemberFileView":
			{
				return createMemberFileVDAO();
			}
			case "MemberFolderView":
			{
				return createMemberFolderVDAO();
			}
			case "MemberFriendView":
			{
				return createMemberFriendVDAO();
			}
			case "MemberSharedView":
			{
				return createMemberSharedVDAO();
			}
			case "SharedFileView":
			{
				return createSharedFileVDAO();
			}
			case "SharedFolderReplyView":
			{
				return createSharedFolderReplyVDAO();
			}
			case "SharedFriendView":
			{
				return createSharedFriendVDAO();
			}
			case "MemberLimitCapacityView":
			{
				return createMemberLimitCapacityVDAO();
			}
			case "MemberFileAuthView":
			{
				return createMemberFileAuthVDAO();
			}
			case "FolderCapacityView":
			{
				return createFolderCapacityVDAO();
			}
			case "MemberShareFolderView":
			{
				return createMemberShareFolderVDAO();
			}
			default:
			{
				return null;
			}
			
		}
	}
	
	private DAO createMemberShareFolderVDAO() {
		// TODO Auto-generated method stub
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("memberShareFolderVDao");
	}

	private DAO createFolderCapacityVDAO() {
		// TODO Auto-generated method stub
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("folderCapacityVDao");
	}

	private DAO createMemberFileAuthVDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("memberFileAuthVDao");
	}
	
	private DAO createMemberLimitCapacityVDAO() {
		// TODO Auto-generated method stub
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("memberLimitCapacityVDao");
	}

	private DAO createFileDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("fileDao");
	}
	
	private DAO createMemberKindDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("memberKindDao");
	}
	
	private DAO createMemberDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("memberDao");
	}
	private DAO createAlarmKindDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("alarmKindDao");
	}
	
	///////////////
	private DAO createAlarmDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("alarmDao");
	}
	
	private DAO createAvailableFileAuthGroupDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("availableFileAuthGroupDao");
	}
	private DAO createAvailableFolderFriendDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("availableFolderFriendDao");
	}
	private DAO createFileBinaryDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("fileBinaryDao");
	}
	private DAO createFolderDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("folderDao");
	}
	private DAO createFriendDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("friendDao");
	}
	private DAO createGroupDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("groupDao");
	}
	private DAO createMediaInfoDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("mediaInfoDao");
	}
	private DAO createReplyDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("replyDao");
	}
	private DAO createSharedFolderDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("sharedFolderDao");
	}
	private DAO createFileGroupVDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("fileGroupVDao");
	}
	private DAO createFolderFileVDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("folderFileVDao");
	}
	private DAO createMemberAlarmVDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("memberAlarmVDao");
	}
	private DAO createMemberFileMediaVDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("memberFileMediaVDao");
	}
	private DAO createMemberFileVDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("memberFileVDao");
	}
	private DAO createMemberFolderVDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("memberFolderVDao");
	}
	private DAO createMemberFriendVDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("memberFriendVDao");
	}
	private DAO createMemberSharedVDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("memberSharedVDao");
	}
	private DAO createSharedFileVDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("sharedFileVDao");
	}
	private DAO createSharedFolderReplyVDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("sharedFolderReplyVDao");
	}
	private DAO createSharedFriendVDAO()
	{
		return (DAO) AppContextSingleton.getInstance().getAppContext().getBean("sharedFriendVDao");
	}

}
