//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Factory.java
//  @ Date : 2014-07-19
//  @ Author : 
//
//


package com.soloud.per.factory;

public interface Factory
{
	public Object create(String objName);
}
